SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.TBLWORKFLOWMASTER', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLWORKFLOWMASTER (
    WORKFLOW_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_ID DEFAULT NEWSEQUENTIALID(),
    WORKFLOW_PUBLIC_ID varchar(48) NOT NULL,
    VISITDATETIME date NOT NULL,
    VISITNUMBER varchar(10) NOT NULL,
    PATIENTID varchar(15) NULL,
    PATIENT_NAME nvarchar(200) NULL,
    WORKFLOW_RUN_NO int NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_RUN DEFAULT 1,
    CASE_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_STATUS DEFAULT 'VERIFY',
    IS_ACTIVE bit NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_ACTIVE DEFAULT 1,
    QUEUE_NO int NULL,
    BLOCK_REASON_CODE varchar(80) NULL,
    BLOCK_REASON_TEXT nvarchar(1000) NULL,
    PAYMENT_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_PAYMENT DEFAULT 'BYPASSED',
    PAYMENT_REFERENCE varchar(100) NULL,
    PAID_AT datetime2(3) NULL,
    PAYMENT_UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_PAYMENT_AT DEFAULT SYSUTCDATETIME(),
    VERIFY_LOCK_TOKEN uniqueidentifier NULL,
    VERIFY_LOCK_SESSION varchar(100) NULL,
    VERIFY_LOCK_OWNER nvarchar(150) NULL,
    VERIFY_LOCK_WORKSTATION varchar(100) NULL,
    VERIFY_LOCKED_AT datetime2(3) NULL,
    VERIFY_LOCK_HEARTBEAT_AT datetime2(3) NULL,
    VERIFY_LOCK_EXPIRES_AT datetime2(3) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_UPDATED DEFAULT SYSUTCDATETIME(),
    COMPLETED_AT datetime2(3) NULL,
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLWORKFLOWMASTER PRIMARY KEY (WORKFLOW_ID),
    CONSTRAINT CK_TBLWORKFLOWMASTER_STATUS CHECK (CASE_STATUS IN ('VERIFY','PENDING','IN_PROGRESS','COMPLETE','BLOCKED','CANCELLED')),
    CONSTRAINT CK_TBLWORKFLOWMASTER_PAYMENT CHECK (PAYMENT_STATUS IN ('WAITING','PAID','FAILED','BYPASSED'))
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'UX_TBLWORKFLOWMASTER_PUBLIC')
  CREATE UNIQUE INDEX UX_TBLWORKFLOWMASTER_PUBLIC ON dbo.TBLWORKFLOWMASTER(WORKFLOW_PUBLIC_ID);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'UX_TBLWORKFLOWMASTER_RUN')
  CREATE UNIQUE INDEX UX_TBLWORKFLOWMASTER_RUN ON dbo.TBLWORKFLOWMASTER(VISITDATETIME, VISITNUMBER, WORKFLOW_RUN_NO);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'UX_TBLWORKFLOWMASTER_ACTIVE_VISIT')
  CREATE UNIQUE INDEX UX_TBLWORKFLOWMASTER_ACTIVE_VISIT ON dbo.TBLWORKFLOWMASTER(VISITDATETIME, VISITNUMBER) WHERE IS_ACTIVE = 1;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'IX_TBLWORKFLOWMASTER_QUEUE')
  CREATE INDEX IX_TBLWORKFLOWMASTER_QUEUE ON dbo.TBLWORKFLOWMASTER(CASE_STATUS, VISITDATETIME, IS_ACTIVE) INCLUDE (VISITNUMBER, PATIENTID, QUEUE_NO);
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEPRESCRIPTIONS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEPRESCRIPTIONS (
    PACKAGE_PRESCRIPTION_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_ID DEFAULT NEWSEQUENTIALID(),
    WORKFLOW_ID uniqueidentifier NOT NULL,
    PRESCRIPTIONNUMBER varchar(16) NOT NULL,
    VERIFY_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_STATUS DEFAULT 'WAITING',
    VERIFIED_BY nvarchar(150) NULL,
    VERIFIED_AT datetime2(3) NULL,
    SOURCE_HASH varchar(64) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_UPDATED DEFAULT SYSUTCDATETIME(),
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLPACKAGEPRESCRIPTIONS PRIMARY KEY (PACKAGE_PRESCRIPTION_ID),
    CONSTRAINT FK_TBLPACKAGEPRESCRIPTIONS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT UQ_TBLPACKAGEPRESCRIPTIONS_WORKFLOW_PN UNIQUE (WORKFLOW_ID, PRESCRIPTIONNUMBER),
    CONSTRAINT CK_TBLPACKAGEPRESCRIPTIONS_STATUS CHECK (VERIFY_STATUS IN ('WAITING','VERIFIED_WAITING','PARTIAL','PACKAGED','SOURCE_CHANGED'))
  );
END;
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEMASTER', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEMASTER (
    PACKAGE_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_ID DEFAULT NEWSEQUENTIALID(),
    WORKFLOW_ID uniqueidentifier NOT NULL,
    PACKAGE_NUMBER varchar(60) NOT NULL,
    BATCH_NO int NOT NULL,
    PACKAGE_PRIORITY varchar(16) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_PRIORITY DEFAULT 'NORMAL',
    PAGE_NOW varchar(32) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_PAGE DEFAULT 'PICKING',
    PACKAGE_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_STATUS DEFAULT 'ACTIVE',
    IS_ACTIVE bit NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_ACTIVE DEFAULT 1,
    VERIFY_NOTE nvarchar(1000) NULL,
    IDEMPOTENCY_KEY varchar(100) NOT NULL,
    VERIFIED_BY nvarchar(150) NULL,
    VERIFY_COMPLETED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_VERIFY_AT DEFAULT SYSUTCDATETIME(),
    PICKED_BY nvarchar(150) NULL,
    PICKING_COMPLETED_AT datetime2(3) NULL,
    MATCHED_BY nvarchar(150) NULL,
    MATCHING_COMPLETED_AT datetime2(3) NULL,
    CHECKED_BY nvarchar(150) NULL,
    CHECKING_COMPLETED_AT datetime2(3) NULL,
    DISPENSED_BY nvarchar(150) NULL,
    DISPENSING_COMPLETED_AT datetime2(3) NULL,
    DISPENSING_PICKUP_STATUS varchar(24) NULL,
    CALL_COUNT int NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_CALL_COUNT DEFAULT 0,
    LAST_CALLED_AT datetime2(3) NULL,
    RECEIVED_AT datetime2(3) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_UPDATED DEFAULT SYSUTCDATETIME(),
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLPACKAGEMASTER PRIMARY KEY (PACKAGE_ID),
    CONSTRAINT FK_TBLPACKAGEMASTER_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT UQ_TBLPACKAGEMASTER_NUMBER UNIQUE (PACKAGE_NUMBER),
    CONSTRAINT UQ_TBLPACKAGEMASTER_BATCH UNIQUE (WORKFLOW_ID, BATCH_NO),
    CONSTRAINT UQ_TBLPACKAGEMASTER_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CK_TBLPACKAGEMASTER_PRIORITY CHECK (PACKAGE_PRIORITY IN ('URGENT','NORMAL')),
    CONSTRAINT CK_TBLPACKAGEMASTER_PAGE CHECK (PAGE_NOW IN ('PICKING','MATCHING','CHECKING','AWAITING_DISPENSING','DISPENSING','COMPLETE')),
    CONSTRAINT CK_TBLPACKAGEMASTER_STATUS CHECK (PACKAGE_STATUS IN ('ACTIVE','COMPLETED','BLOCKED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEMASTER_PICKUP CHECK (DISPENSING_PICKUP_STATUS IS NULL OR DISPENSING_PICKUP_STATUS IN ('WAITING_CALL','CALLED_WAITING','RECEIVED'))
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name = N'UX_TBLPACKAGEMASTER_ACTIVE_WORKFLOW')
  CREATE UNIQUE INDEX UX_TBLPACKAGEMASTER_ACTIVE_WORKFLOW ON dbo.TBLPACKAGEMASTER(WORKFLOW_ID) WHERE IS_ACTIVE = 1;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name = N'IX_TBLPACKAGEMASTER_PAGE')
  CREATE INDEX IX_TBLPACKAGEMASTER_PAGE ON dbo.TBLPACKAGEMASTER(PAGE_NOW, IS_ACTIVE, UPDATED_AT DESC) INCLUDE (WORKFLOW_ID, PACKAGE_NUMBER, PACKAGE_PRIORITY);
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEITEMS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEITEMS (
    PACKAGE_ITEM_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_ID DEFAULT NEWSEQUENTIALID(),
    PACKAGE_ID uniqueidentifier NOT NULL,
    WORKFLOW_ID uniqueidentifier NOT NULL,
    VISITDATETIME date NOT NULL,
    VISITNUMBER varchar(10) NOT NULL,
    PRESCRIPTIONNUMBER varchar(16) NOT NULL,
    MEDICINECODE varchar(30) NOT NULL,
    ITEMSEQ int NOT NULL,
    SOURCE_CREATED_AT datetime2(3) NULL,
    SOURCE_HASH varchar(64) NULL,
    SOURCE_URGENCY_CODE varchar(40) NULL,
    COMMERCIALNAME nvarchar(300) NULL,
    ORDERQTY decimal(18,2) NULL,
    ORDERUNITCODE varchar(32) NULL,
    DOSEMEMO_TH nvarchar(max) NULL,
    PICKING_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_PICKING DEFAULT 'WAITING',
    MATCHING_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_MATCHING DEFAULT 'WAITING',
    CHECKING_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_CHECKING DEFAULT 'WAITING',
    PICKED_BY nvarchar(150) NULL,
    PICKED_AT datetime2(3) NULL,
    MATCHED_BY nvarchar(150) NULL,
    MATCHED_AT datetime2(3) NULL,
    CHECKED_BY nvarchar(150) NULL,
    CHECKED_AT datetime2(3) NULL,
    LABEL_PUBLIC_ID varchar(60) NOT NULL,
    QR_TOKEN varchar(100) NOT NULL,
    LABEL_PAYLOAD nvarchar(max) NULL,
    LABEL_TEMPLATE_VERSION int NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_LABEL_VERSION DEFAULT 1,
    LABEL_STATUS varchar(32) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_LABEL_STATUS DEFAULT 'READY_TO_PRINT',
    PRINT_COUNT int NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_PRINT_COUNT DEFAULT 0,
    PRINTED_AT datetime2(3) NULL,
    LABEL_CHECKED_AT datetime2(3) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_UPDATED DEFAULT SYSUTCDATETIME(),
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLPACKAGEITEMS PRIMARY KEY (PACKAGE_ITEM_ID),
    CONSTRAINT FK_TBLPACKAGEITEMS_PACKAGE FOREIGN KEY (PACKAGE_ID) REFERENCES dbo.TBLPACKAGEMASTER(PACKAGE_ID),
    CONSTRAINT FK_TBLPACKAGEITEMS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT UQ_TBLPACKAGEITEMS_SOURCE UNIQUE (WORKFLOW_ID, PRESCRIPTIONNUMBER, MEDICINECODE, ITEMSEQ),
    CONSTRAINT UQ_TBLPACKAGEITEMS_LABEL_PUBLIC UNIQUE (LABEL_PUBLIC_ID),
    CONSTRAINT UQ_TBLPACKAGEITEMS_QR UNIQUE (QR_TOKEN),
    CONSTRAINT CK_TBLPACKAGEITEMS_PICKING CHECK (PICKING_STATUS IN ('WAITING','COMPLETED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEITEMS_MATCHING CHECK (MATCHING_STATUS IN ('WAITING','COMPLETED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEITEMS_CHECKING CHECK (CHECKING_STATUS IN ('WAITING','COMPLETED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEITEMS_LABEL_STATUS CHECK (LABEL_STATUS IN ('READY_TO_PRINT','PRINTED','CHECKED','VOIDED'))
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEITEMS') AND name = N'IX_TBLPACKAGEITEMS_PACKAGE')
  CREATE INDEX IX_TBLPACKAGEITEMS_PACKAGE ON dbo.TBLPACKAGEITEMS(PACKAGE_ID, PRESCRIPTIONNUMBER, ITEMSEQ);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEITEMS') AND name = N'IX_TBLPACKAGEITEMS_MEDICINE')
  CREATE INDEX IX_TBLPACKAGEITEMS_MEDICINE ON dbo.TBLPACKAGEITEMS(PACKAGE_ID, MEDICINECODE) INCLUDE (MATCHING_STATUS, CHECKING_STATUS, QR_TOKEN);
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEEVENTS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEEVENTS (
    EVENT_ID bigint IDENTITY(1,1) NOT NULL,
    WORKFLOW_ID uniqueidentifier NOT NULL,
    PACKAGE_ID uniqueidentifier NULL,
    PACKAGE_ITEM_ID uniqueidentifier NULL,
    EVENT_TYPE varchar(60) NOT NULL,
    FROM_PAGE varchar(32) NULL,
    TO_PAGE varchar(32) NULL,
    SCAN_TYPE varchar(40) NULL,
    SCANNED_VALUE varchar(200) NULL,
    EXPECTED_VALUE varchar(200) NULL,
    RESULT varchar(32) NULL,
    FAILURE_REASON nvarchar(1000) NULL,
    ACTOR_ID varchar(80) NULL,
    ACTOR_NAME nvarchar(150) NULL,
    WORKSTATION_CODE varchar(100) NULL,
    EVENT_DATA nvarchar(max) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEEVENTS_CREATED DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_TBLPACKAGEEVENTS PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_TBLPACKAGEEVENTS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT FK_TBLPACKAGEEVENTS_PACKAGE FOREIGN KEY (PACKAGE_ID) REFERENCES dbo.TBLPACKAGEMASTER(PACKAGE_ID),
    CONSTRAINT FK_TBLPACKAGEEVENTS_ITEM FOREIGN KEY (PACKAGE_ITEM_ID) REFERENCES dbo.TBLPACKAGEITEMS(PACKAGE_ITEM_ID),
    CONSTRAINT CK_TBLPACKAGEEVENTS_RESULT CHECK (RESULT IS NULL OR RESULT IN ('SUCCESS','MATCHED','MISMATCHED','REJECTED','FAILED'))
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEEVENTS') AND name = N'IX_TBLPACKAGEEVENTS_WORKFLOW')
  CREATE INDEX IX_TBLPACKAGEEVENTS_WORKFLOW ON dbo.TBLPACKAGEEVENTS(WORKFLOW_ID, CREATED_AT DESC);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEEVENTS') AND name = N'IX_TBLPACKAGEEVENTS_PACKAGE')
  CREATE INDEX IX_TBLPACKAGEEVENTS_PACKAGE ON dbo.TBLPACKAGEEVENTS(PACKAGE_ID, CREATED_AT DESC) WHERE PACKAGE_ID IS NOT NULL;
GO

