SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;

IF EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'workflow')
BEGIN
  IF OBJECT_ID(N'workflow.INTEGRATION_OUTBOX', N'U') IS NOT NULL DROP TABLE workflow.INTEGRATION_OUTBOX;
  IF OBJECT_ID(N'workflow.INTEGRATION_INBOX', N'U') IS NOT NULL DROP TABLE workflow.INTEGRATION_INBOX;
  IF OBJECT_ID(N'workflow.TRANSITION_HISTORY', N'U') IS NOT NULL DROP TABLE workflow.TRANSITION_HISTORY;
  IF OBJECT_ID(N'workflow.SCAN_EVENT', N'U') IS NOT NULL DROP TABLE workflow.SCAN_EVENT;
  IF OBJECT_ID(N'workflow.PAYMENT_GATE', N'U') IS NOT NULL DROP TABLE workflow.PAYMENT_GATE;
  IF OBJECT_ID(N'workflow.PICKING_TASK_ITEM', N'U') IS NOT NULL DROP TABLE workflow.PICKING_TASK_ITEM;
  IF OBJECT_ID(N'workflow.PICKING_TASK', N'U') IS NOT NULL DROP TABLE workflow.PICKING_TASK;
  IF OBJECT_ID(N'workflow.PRINT_JOB', N'U') IS NOT NULL DROP TABLE workflow.PRINT_JOB;
  IF OBJECT_ID(N'workflow.LABEL', N'U') IS NOT NULL DROP TABLE workflow.LABEL;
  IF OBJECT_ID(N'workflow.PACKAGE_ITEM', N'U') IS NOT NULL DROP TABLE workflow.PACKAGE_ITEM;
  IF OBJECT_ID(N'workflow.PACKAGE', N'U') IS NOT NULL DROP TABLE workflow.PACKAGE;
  IF OBJECT_ID(N'workflow.ITEM_PROGRESS', N'U') IS NOT NULL DROP TABLE workflow.ITEM_PROGRESS;
  IF OBJECT_ID(N'workflow.ITEM_SNAPSHOT', N'U') IS NOT NULL DROP TABLE workflow.ITEM_SNAPSHOT;
  IF OBJECT_ID(N'workflow.PRESCRIPTION_SNAPSHOT', N'U') IS NOT NULL DROP TABLE workflow.PRESCRIPTION_SNAPSHOT;
  IF OBJECT_ID(N'workflow.JOB', N'U') IS NOT NULL DROP TABLE workflow.JOB;
  EXEC(N'DROP SCHEMA workflow');
END;

COMMIT TRANSACTION;
GO

