SET NOCOUNT ON;

IF SCHEMA_ID(N'workflow') IS NOT NULL
  THROW 51000, 'Legacy workflow schema still exists.', 1;

IF OBJECT_ID(N'dbo.TBLORX', N'U') IS NULL
  THROW 51000, 'Source table dbo.TBLORX was not found.', 1;
IF OBJECT_ID(N'dbo.TBLORXITEMS', N'U') IS NULL
  THROW 51000, 'Source table dbo.TBLORXITEMS was not found.', 1;

IF COL_LENGTH(N'dbo.TBLORXITEMS', N'VISITDATETIME') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.VISITDATETIME was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'VISITNUMBER') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.VISITNUMBER was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'PRESCRIPTIONNUMBER') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.PRESCRIPTIONNUMBER was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'MEDICINECODE') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.MEDICINECODE was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'ITEMSEQ') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.ITEMSEQ was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'IS_DELETED') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.IS_DELETED was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'CANCELSTATUS') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.CANCELSTATUS was not found.', 1;

IF OBJECT_ID(N'dbo.TBLWORKFLOWMASTER', N'U') IS NULL
  THROW 51000, 'dbo.TBLWORKFLOWMASTER was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEPRESCRIPTIONS', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEPRESCRIPTIONS was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEMASTER', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEMASTER was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEITEMS', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEITEMS was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEEVENTS', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEEVENTS was not created.', 1;
