SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.TBLWORKFLOWMASTER', N'U') IS NULL
  THROW 51000, 'dbo.TBLWORKFLOWMASTER was not found. Run 001_create_package_workflow_schema.sql first.', 1;
GO

BEGIN TRANSACTION;

IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_DRAFT') IS NULL
  ALTER TABLE dbo.TBLWORKFLOWMASTER ADD VERIFY_NOTE_DRAFT nvarchar(1000) NULL;

IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_AT') IS NULL
  ALTER TABLE dbo.TBLWORKFLOWMASTER ADD VERIFY_NOTE_UPDATED_AT datetime2(3) NULL;

IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_BY') IS NULL
  ALTER TABLE dbo.TBLWORKFLOWMASTER ADD VERIFY_NOTE_UPDATED_BY nvarchar(150) NULL;

COMMIT TRANSACTION;
GO

IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_DRAFT') IS NULL
  THROW 51000, 'VERIFY_NOTE_DRAFT installation failed.', 1;
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_AT') IS NULL
  THROW 51000, 'VERIFY_NOTE_UPDATED_AT installation failed.', 1;
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_BY') IS NULL
  THROW 51000, 'VERIFY_NOTE_UPDATED_BY installation failed.', 1;

SELECT
  COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_DRAFT') AS VERIFY_NOTE_DRAFT_BYTES,
  COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_AT') AS VERIFY_NOTE_UPDATED_AT_BYTES,
  COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_BY') AS VERIFY_NOTE_UPDATED_BY_BYTES;
GO
