SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.TBLHOSPITALQUEUESTEP', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLHOSPITALQUEUESTEP (
    VISIT_DATE date NOT NULL,
    VN varchar(50) NOT NULL,
    STEP_ID varchar(2) NOT NULL,
    FIRST_READY_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLHOSPITALQUEUESTEP_FIRST DEFAULT SYSUTCDATETIME(),
    LAST_RECEIVED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLHOSPITALQUEUESTEP_LAST DEFAULT SYSUTCDATETIME(),
    RECEIPT_COUNT int NOT NULL CONSTRAINT DF_TBLHOSPITALQUEUESTEP_COUNT DEFAULT 1,
    APPLIED_WORKFLOW_ID uniqueidentifier NULL,
    CONSTRAINT PK_TBLHOSPITALQUEUESTEP PRIMARY KEY (VISIT_DATE, VN),
    CONSTRAINT CK_TBLHOSPITALQUEUESTEP_STEP CHECK (STEP_ID = '04')
  );
END;
GO

IF OBJECT_ID(N'dbo.TBLDISPENSINGCHANNELCLAIMS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLDISPENSINGCHANNELCLAIMS (
    CLAIM_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLDISPENSINGCHANNELCLAIMS_ID DEFAULT NEWSEQUENTIALID(),
    CHANNEL_NO tinyint NOT NULL,
    CLAIM_TOKEN_HASH varbinary(32) NOT NULL,
    CLAIMED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLDISPENSINGCHANNELCLAIMS_AT DEFAULT SYSUTCDATETIME(),
    RELEASED_AT datetime2(3) NULL,
    RELEASE_REASON nvarchar(200) NULL,
    CONSTRAINT PK_TBLDISPENSINGCHANNELCLAIMS PRIMARY KEY (CLAIM_ID),
    CONSTRAINT CK_TBLDISPENSINGCHANNELCLAIMS_CHANNEL CHECK (CHANNEL_NO BETWEEN 1 AND 8)
  );
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TBLDISPENSINGCHANNELCLAIMS') AND name=N'UX_TBLDISPENSINGCHANNELCLAIMS_ACTIVE')
  CREATE UNIQUE INDEX UX_TBLDISPENSINGCHANNELCLAIMS_ACTIVE ON dbo.TBLDISPENSINGCHANNELCLAIMS(CHANNEL_NO) WHERE RELEASED_AT IS NULL;
GO

IF COL_LENGTH(N'dbo.TBLPACKAGEMASTER', N'DISPENSING_CHANNEL') IS NULL
  ALTER TABLE dbo.TBLPACKAGEMASTER ADD DISPENSING_CHANNEL tinyint NULL;
GO
IF COL_LENGTH(N'dbo.TBLPACKAGEMASTER', N'QUEUE_READY_AT') IS NULL
  ALTER TABLE dbo.TBLPACKAGEMASTER ADD QUEUE_READY_AT datetime2(3) NULL;
GO
IF COL_LENGTH(N'dbo.TBLPACKAGEMASTER', N'MISSED_AT') IS NULL
  ALTER TABLE dbo.TBLPACKAGEMASTER ADD MISSED_AT datetime2(3) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name=N'CK_TBLPACKAGEMASTER_DISPENSING_CHANNEL')
  ALTER TABLE dbo.TBLPACKAGEMASTER ADD CONSTRAINT CK_TBLPACKAGEMASTER_DISPENSING_CHANNEL CHECK (DISPENSING_CHANNEL IS NULL OR DISPENSING_CHANNEL BETWEEN 1 AND 8);
GO
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER')
  AND name=N'CK_TBLPACKAGEMASTER_PICKUP' AND definition NOT LIKE '%MISSED_CALL%')
  ALTER TABLE dbo.TBLPACKAGEMASTER DROP CONSTRAINT CK_TBLPACKAGEMASTER_PICKUP;
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER')
  AND name=N'CK_TBLPACKAGEMASTER_PICKUP')
  ALTER TABLE dbo.TBLPACKAGEMASTER WITH CHECK ADD CONSTRAINT CK_TBLPACKAGEMASTER_PICKUP
    CHECK (DISPENSING_PICKUP_STATUS IS NULL OR DISPENSING_PICKUP_STATUS IN ('WAITING_CALL','CALLED_WAITING','MISSED_CALL','RECEIVED'));
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name=N'IX_TBLPACKAGEMASTER_DISPENSING_QUEUE')
  CREATE INDEX IX_TBLPACKAGEMASTER_DISPENSING_QUEUE ON dbo.TBLPACKAGEMASTER(PAGE_NOW, DISPENSING_CHANNEL, QUEUE_READY_AT, PACKAGE_ID)
    INCLUDE (WORKFLOW_ID, DISPENSING_PICKUP_STATUS, CHECKING_COMPLETED_AT, RECEIVED_AT);
GO

IF COL_LENGTH(N'dbo.TBLPACKAGEEVENTS', N'ACTION_ID') IS NULL
  ALTER TABLE dbo.TBLPACKAGEEVENTS ADD ACTION_ID uniqueidentifier NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEEVENTS') AND name=N'UX_TBLPACKAGEEVENTS_ACTION_ID')
  CREATE UNIQUE INDEX UX_TBLPACKAGEEVENTS_ACTION_ID ON dbo.TBLPACKAGEEVENTS(ACTION_ID) WHERE ACTION_ID IS NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLHOSPITALQUEUESTEP'))
  ALTER TABLE dbo.TBLHOSPITALQUEUESTEP ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLDISPENSINGCHANNELCLAIMS'))
  ALTER TABLE dbo.TBLDISPENSINGCHANNELCLAIMS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

SELECT name FROM sys.tables WHERE name IN ('TBLHOSPITALQUEUESTEP','TBLDISPENSINGCHANNELCLAIMS');
SELECT name FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name IN ('DISPENSING_CHANNEL','QUEUE_READY_AT','MISSED_AT');
GO
