/*
  JurapornWeb Full-stack Database Installer
  GENERATED FILE - DO NOT EDIT DIRECTLY

  Regenerate with: npm run db:bundle
  Included: 001 package workflow, 005 realtime, 003/006 validation
  Excluded: 002 destructive cleanup, 004 test seed, 007 rollback, 008 already folded into 001

  Prerequisite: select an existing copied hospital database containing the source tables.
  This file is intentionally rerunnable and does not insert test data.
*/

-- ===== Preflight: no database changes occur before this batch passes =====

SET NOCOUNT ON;
SET XACT_ABORT ON;

IF DB_NAME() IN (N'master', N'model', N'msdb', N'tempdb')
  THROW 51000, 'Choose the copied hospital application database before installing JurapornWeb.', 1;

IF SCHEMA_ID(N'workflow') IS NOT NULL
  THROW 51000, 'Legacy schema [workflow] exists. Back up and review 002_drop_legacy_workflow_schema.sql separately before installation.', 1;

IF HAS_PERMS_BY_NAME(DB_NAME(), 'DATABASE', 'ALTER') <> 1
  THROW 51000, 'Installer account requires ALTER permission on the selected database.', 1;
IF HAS_PERMS_BY_NAME(DB_NAME(), 'DATABASE', 'CREATE TABLE') <> 1
  THROW 51000, 'Installer account requires CREATE TABLE permission on the selected database.', 1;
IF HAS_PERMS_BY_NAME(N'dbo', 'SCHEMA', 'ALTER') <> 1
  THROW 51000, 'Installer account requires ALTER permission on schema dbo.', 1;

DECLARE @RequiredTables TABLE (TABLE_NAME sysname NOT NULL PRIMARY KEY);
INSERT INTO @RequiredTables (TABLE_NAME)
VALUES
  (N'TBLORX'), (N'TBLORXITEMS'), (N'TBLPATIENT'), (N'TBLMEDITEMSINFO'),
  (N'TBLDOCTOR'), (N'TBLDEPT'), (N'TBLALLERGY'), (N'DrugInteraction');

DECLARE @MissingTable sysname = (
  SELECT TOP (1) required.TABLE_NAME
  FROM @RequiredTables AS required
  WHERE OBJECT_ID(N'dbo.' + required.TABLE_NAME, N'U') IS NULL
  ORDER BY required.TABLE_NAME
);
IF @MissingTable IS NOT NULL
  THROW 51000, 'A required source table is missing. This installer requires the existing hospital database (TBLORX, TBLORXITEMS, patient, allergy and reference tables).', 1;

DECLARE @TrackedSourceTables TABLE (TABLE_NAME sysname NOT NULL PRIMARY KEY);
INSERT INTO @TrackedSourceTables (TABLE_NAME)
VALUES (N'TBLORX'), (N'TBLORXITEMS'), (N'TBLPATIENT'), (N'TBLMEDITEMSINFO'), (N'TBLDOCTOR'), (N'TBLDEPT');

DECLARE @MissingPrimaryKey sysname = (
  SELECT TOP (1) tracked.TABLE_NAME
  FROM @TrackedSourceTables AS tracked
  WHERE NOT EXISTS (
    SELECT 1
    FROM sys.indexes AS index_info
    WHERE index_info.object_id = OBJECT_ID(N'dbo.' + tracked.TABLE_NAME)
      AND index_info.is_primary_key = 1
  )
  ORDER BY tracked.TABLE_NAME
);
IF @MissingPrimaryKey IS NOT NULL
  THROW 51000, 'A source table required by Change Tracking has no Primary Key. No key is created automatically; ask the DBA to review the source schema.', 1;

DECLARE @RequiredColumns TABLE (TABLE_NAME sysname NOT NULL, COLUMN_NAME sysname NOT NULL, PRIMARY KEY (TABLE_NAME, COLUMN_NAME));
INSERT INTO @RequiredColumns (TABLE_NAME, COLUMN_NAME)
VALUES
  (N'TBLORX', N'VISITDATETIME'), (N'TBLORX', N'VISITNUMBER'),
  (N'TBLORX', N'PRESCRIPTIONNUMBER'), (N'TBLORX', N'PATIENTID'),
  (N'TBLORXITEMS', N'VISITDATETIME'), (N'TBLORXITEMS', N'VISITNUMBER'),
  (N'TBLORXITEMS', N'PRESCRIPTIONNUMBER'), (N'TBLORXITEMS', N'MEDICINECODE'),
  (N'TBLORXITEMS', N'ITEMSEQ'), (N'TBLORXITEMS', N'IS_DELETED'),
  (N'TBLORXITEMS', N'CANCELSTATUS'), (N'TBLPATIENT', N'PATIENTID'),
  (N'TBLMEDITEMSINFO', N'MEDICINECODE'), (N'TBLDOCTOR', N'DOCTORCODE'),
  (N'TBLDEPT', N'DEPTCODE'), (N'TBLALLERGY', N'HN'),
  (N'TBLALLERGY', N'MEDICINECODE'), (N'DrugInteraction', N'StockCode'),
  (N'DrugInteraction', N'WithStockCode');

DECLARE @MissingColumn nvarchar(260) = (
  SELECT TOP (1) required.TABLE_NAME + N'.' + required.COLUMN_NAME
  FROM @RequiredColumns AS required
  WHERE COL_LENGTH(N'dbo.' + required.TABLE_NAME, required.COLUMN_NAME) IS NULL
  ORDER BY required.TABLE_NAME, required.COLUMN_NAME
);
IF @MissingColumn IS NOT NULL
  THROW 51000, 'A required source column is missing. The copied hospital database is not compatible with this JurapornWeb installer.', 1;

PRINT 'JurapornWeb preflight passed for database [' + DB_NAME() + '].';
GO

-- ===== Source: 001_create_package_workflow_schema.sql =====

SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.TBLWORKFLOWMASTER', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLWORKFLOWMASTER (
    WORKFLOW_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_ID DEFAULT NEWSEQUENTIALID(),
    WORKFLOW_PUBLIC_ID varchar(48) NOT NULL,
    VISITDATETIME date NOT NULL,
    VISITNUMBER varchar(10) NOT NULL,
    PATIENTID varchar(15) NULL,
    PATIENT_NAME nvarchar(200) NULL,
    WORKFLOW_RUN_NO int NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_RUN DEFAULT 1,
    CASE_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_STATUS DEFAULT 'VERIFY',
    IS_ACTIVE bit NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_ACTIVE DEFAULT 1,
    QUEUE_NO int NULL,
    BLOCK_REASON_CODE varchar(80) NULL,
    BLOCK_REASON_TEXT nvarchar(1000) NULL,
    PAYMENT_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_PAYMENT DEFAULT 'BYPASSED',
    PAYMENT_REFERENCE varchar(100) NULL,
    PAID_AT datetime2(3) NULL,
    PAYMENT_UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_PAYMENT_AT DEFAULT SYSUTCDATETIME(),
    VERIFY_LOCK_TOKEN uniqueidentifier NULL,
    VERIFY_LOCK_SESSION varchar(100) NULL,
    VERIFY_LOCK_OWNER nvarchar(150) NULL,
    VERIFY_LOCK_WORKSTATION varchar(100) NULL,
    VERIFY_LOCKED_AT datetime2(3) NULL,
    VERIFY_LOCK_HEARTBEAT_AT datetime2(3) NULL,
    VERIFY_LOCK_EXPIRES_AT datetime2(3) NULL,
    VERIFY_NOTE_DRAFT nvarchar(1000) NULL,
    VERIFY_NOTE_UPDATED_AT datetime2(3) NULL,
    VERIFY_NOTE_UPDATED_BY nvarchar(150) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_UPDATED DEFAULT SYSUTCDATETIME(),
    COMPLETED_AT datetime2(3) NULL,
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLWORKFLOWMASTER PRIMARY KEY (WORKFLOW_ID),
    CONSTRAINT CK_TBLWORKFLOWMASTER_STATUS CHECK (CASE_STATUS IN ('VERIFY','PENDING','IN_PROGRESS','COMPLETE','BLOCKED','CANCELLED')),
    CONSTRAINT CK_TBLWORKFLOWMASTER_PAYMENT CHECK (PAYMENT_STATUS IN ('WAITING','PAID','FAILED','BYPASSED'))
  );
END;
GO

-- Keep the current installer idempotent for databases created by an older 001.
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_DRAFT') IS NULL
  ALTER TABLE dbo.TBLWORKFLOWMASTER ADD VERIFY_NOTE_DRAFT nvarchar(1000) NULL;
GO
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_AT') IS NULL
  ALTER TABLE dbo.TBLWORKFLOWMASTER ADD VERIFY_NOTE_UPDATED_AT datetime2(3) NULL;
GO
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_BY') IS NULL
  ALTER TABLE dbo.TBLWORKFLOWMASTER ADD VERIFY_NOTE_UPDATED_BY nvarchar(150) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'UX_TBLWORKFLOWMASTER_PUBLIC')
  CREATE UNIQUE INDEX UX_TBLWORKFLOWMASTER_PUBLIC ON dbo.TBLWORKFLOWMASTER(WORKFLOW_PUBLIC_ID);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'UX_TBLWORKFLOWMASTER_RUN')
  CREATE UNIQUE INDEX UX_TBLWORKFLOWMASTER_RUN ON dbo.TBLWORKFLOWMASTER(VISITDATETIME, VISITNUMBER, WORKFLOW_RUN_NO);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'UX_TBLWORKFLOWMASTER_ACTIVE_VISIT')
  CREATE UNIQUE INDEX UX_TBLWORKFLOWMASTER_ACTIVE_VISIT ON dbo.TBLWORKFLOWMASTER(VISITDATETIME, VISITNUMBER) WHERE IS_ACTIVE = 1;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'IX_TBLWORKFLOWMASTER_QUEUE')
  CREATE INDEX IX_TBLWORKFLOWMASTER_QUEUE ON dbo.TBLWORKFLOWMASTER(CASE_STATUS, VISITDATETIME, IS_ACTIVE) INCLUDE (VISITNUMBER, PATIENTID, QUEUE_NO);
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEPRESCRIPTIONS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEPRESCRIPTIONS (
    PACKAGE_PRESCRIPTION_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_ID DEFAULT NEWSEQUENTIALID(),
    WORKFLOW_ID uniqueidentifier NOT NULL,
    PRESCRIPTIONNUMBER varchar(16) NOT NULL,
    VERIFY_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_STATUS DEFAULT 'WAITING',
    VERIFIED_BY nvarchar(150) NULL,
    VERIFIED_AT datetime2(3) NULL,
    SOURCE_HASH varchar(64) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_UPDATED DEFAULT SYSUTCDATETIME(),
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLPACKAGEPRESCRIPTIONS PRIMARY KEY (PACKAGE_PRESCRIPTION_ID),
    CONSTRAINT FK_TBLPACKAGEPRESCRIPTIONS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT UQ_TBLPACKAGEPRESCRIPTIONS_WORKFLOW_PN UNIQUE (WORKFLOW_ID, PRESCRIPTIONNUMBER),
    CONSTRAINT CK_TBLPACKAGEPRESCRIPTIONS_STATUS CHECK (VERIFY_STATUS IN ('WAITING','VERIFIED_WAITING','PARTIAL','PACKAGED','SOURCE_CHANGED'))
  );
END;
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEMASTER', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEMASTER (
    PACKAGE_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_ID DEFAULT NEWSEQUENTIALID(),
    WORKFLOW_ID uniqueidentifier NOT NULL,
    PACKAGE_NUMBER varchar(60) NOT NULL,
    BATCH_NO int NOT NULL,
    PACKAGE_PRIORITY varchar(16) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_PRIORITY DEFAULT 'NORMAL',
    PAGE_NOW varchar(32) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_PAGE DEFAULT 'PICKING',
    PACKAGE_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_STATUS DEFAULT 'ACTIVE',
    IS_ACTIVE bit NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_ACTIVE DEFAULT 1,
    VERIFY_NOTE nvarchar(1000) NULL,
    IDEMPOTENCY_KEY varchar(100) NOT NULL,
    VERIFIED_BY nvarchar(150) NULL,
    VERIFY_COMPLETED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_VERIFY_AT DEFAULT SYSUTCDATETIME(),
    PICKED_BY nvarchar(150) NULL,
    PICKING_COMPLETED_AT datetime2(3) NULL,
    MATCHED_BY nvarchar(150) NULL,
    MATCHING_COMPLETED_AT datetime2(3) NULL,
    CHECKED_BY nvarchar(150) NULL,
    CHECKING_COMPLETED_AT datetime2(3) NULL,
    DISPENSED_BY nvarchar(150) NULL,
    DISPENSING_COMPLETED_AT datetime2(3) NULL,
    DISPENSING_PICKUP_STATUS varchar(24) NULL,
    CALL_COUNT int NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_CALL_COUNT DEFAULT 0,
    LAST_CALLED_AT datetime2(3) NULL,
    RECEIVED_AT datetime2(3) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_UPDATED DEFAULT SYSUTCDATETIME(),
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLPACKAGEMASTER PRIMARY KEY (PACKAGE_ID),
    CONSTRAINT FK_TBLPACKAGEMASTER_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT UQ_TBLPACKAGEMASTER_NUMBER UNIQUE (PACKAGE_NUMBER),
    CONSTRAINT UQ_TBLPACKAGEMASTER_BATCH UNIQUE (WORKFLOW_ID, BATCH_NO),
    CONSTRAINT UQ_TBLPACKAGEMASTER_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CK_TBLPACKAGEMASTER_PRIORITY CHECK (PACKAGE_PRIORITY IN ('URGENT','NORMAL')),
    CONSTRAINT CK_TBLPACKAGEMASTER_PAGE CHECK (PAGE_NOW IN ('PICKING','MATCHING','CHECKING','AWAITING_DISPENSING','DISPENSING','COMPLETE')),
    CONSTRAINT CK_TBLPACKAGEMASTER_STATUS CHECK (PACKAGE_STATUS IN ('ACTIVE','COMPLETED','BLOCKED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEMASTER_PICKUP CHECK (DISPENSING_PICKUP_STATUS IS NULL OR DISPENSING_PICKUP_STATUS IN ('WAITING_CALL','CALLED_WAITING','RECEIVED'))
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name = N'UX_TBLPACKAGEMASTER_ACTIVE_WORKFLOW')
  CREATE UNIQUE INDEX UX_TBLPACKAGEMASTER_ACTIVE_WORKFLOW ON dbo.TBLPACKAGEMASTER(WORKFLOW_ID) WHERE IS_ACTIVE = 1;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name = N'IX_TBLPACKAGEMASTER_PAGE')
  CREATE INDEX IX_TBLPACKAGEMASTER_PAGE ON dbo.TBLPACKAGEMASTER(PAGE_NOW, IS_ACTIVE, UPDATED_AT DESC) INCLUDE (WORKFLOW_ID, PACKAGE_NUMBER, PACKAGE_PRIORITY);
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEITEMS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEITEMS (
    PACKAGE_ITEM_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_ID DEFAULT NEWSEQUENTIALID(),
    PACKAGE_ID uniqueidentifier NOT NULL,
    WORKFLOW_ID uniqueidentifier NOT NULL,
    VISITDATETIME date NOT NULL,
    VISITNUMBER varchar(10) NOT NULL,
    PRESCRIPTIONNUMBER varchar(16) NOT NULL,
    MEDICINECODE varchar(30) NOT NULL,
    ITEMSEQ int NOT NULL,
    SOURCE_CREATED_AT datetime2(3) NULL,
    SOURCE_HASH varchar(64) NULL,
    SOURCE_URGENCY_CODE varchar(40) NULL,
    COMMERCIALNAME nvarchar(300) NULL,
    ORDERQTY decimal(18,2) NULL,
    ORDERUNITCODE varchar(32) NULL,
    DOSEMEMO_TH nvarchar(max) NULL,
    PICKING_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_PICKING DEFAULT 'WAITING',
    MATCHING_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_MATCHING DEFAULT 'WAITING',
    CHECKING_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_CHECKING DEFAULT 'WAITING',
    PICKED_BY nvarchar(150) NULL,
    PICKED_AT datetime2(3) NULL,
    MATCHED_BY nvarchar(150) NULL,
    MATCHED_AT datetime2(3) NULL,
    CHECKED_BY nvarchar(150) NULL,
    CHECKED_AT datetime2(3) NULL,
    LABEL_PUBLIC_ID varchar(60) NOT NULL,
    QR_TOKEN varchar(100) NOT NULL,
    LABEL_PAYLOAD nvarchar(max) NULL,
    LABEL_TEMPLATE_VERSION int NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_LABEL_VERSION DEFAULT 1,
    LABEL_STATUS varchar(32) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_LABEL_STATUS DEFAULT 'READY_TO_PRINT',
    PRINT_COUNT int NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_PRINT_COUNT DEFAULT 0,
    PRINTED_AT datetime2(3) NULL,
    LABEL_CHECKED_AT datetime2(3) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_UPDATED DEFAULT SYSUTCDATETIME(),
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLPACKAGEITEMS PRIMARY KEY (PACKAGE_ITEM_ID),
    CONSTRAINT FK_TBLPACKAGEITEMS_PACKAGE FOREIGN KEY (PACKAGE_ID) REFERENCES dbo.TBLPACKAGEMASTER(PACKAGE_ID),
    CONSTRAINT FK_TBLPACKAGEITEMS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT UQ_TBLPACKAGEITEMS_SOURCE UNIQUE (WORKFLOW_ID, PRESCRIPTIONNUMBER, MEDICINECODE, ITEMSEQ),
    CONSTRAINT UQ_TBLPACKAGEITEMS_LABEL_PUBLIC UNIQUE (LABEL_PUBLIC_ID),
    CONSTRAINT UQ_TBLPACKAGEITEMS_QR UNIQUE (QR_TOKEN),
    CONSTRAINT CK_TBLPACKAGEITEMS_PICKING CHECK (PICKING_STATUS IN ('WAITING','COMPLETED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEITEMS_MATCHING CHECK (MATCHING_STATUS IN ('WAITING','COMPLETED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEITEMS_CHECKING CHECK (CHECKING_STATUS IN ('WAITING','COMPLETED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEITEMS_LABEL_STATUS CHECK (LABEL_STATUS IN ('READY_TO_PRINT','PRINTED','CHECKED','VOIDED'))
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEITEMS') AND name = N'IX_TBLPACKAGEITEMS_PACKAGE')
  CREATE INDEX IX_TBLPACKAGEITEMS_PACKAGE ON dbo.TBLPACKAGEITEMS(PACKAGE_ID, PRESCRIPTIONNUMBER, ITEMSEQ);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEITEMS') AND name = N'IX_TBLPACKAGEITEMS_MEDICINE')
  CREATE INDEX IX_TBLPACKAGEITEMS_MEDICINE ON dbo.TBLPACKAGEITEMS(PACKAGE_ID, MEDICINECODE) INCLUDE (MATCHING_STATUS, CHECKING_STATUS, QR_TOKEN);
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEEVENTS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEEVENTS (
    EVENT_ID bigint IDENTITY(1,1) NOT NULL,
    WORKFLOW_ID uniqueidentifier NOT NULL,
    PACKAGE_ID uniqueidentifier NULL,
    PACKAGE_ITEM_ID uniqueidentifier NULL,
    EVENT_TYPE varchar(60) NOT NULL,
    FROM_PAGE varchar(32) NULL,
    TO_PAGE varchar(32) NULL,
    SCAN_TYPE varchar(40) NULL,
    SCANNED_VALUE varchar(200) NULL,
    EXPECTED_VALUE varchar(200) NULL,
    RESULT varchar(32) NULL,
    FAILURE_REASON nvarchar(1000) NULL,
    ACTOR_ID varchar(80) NULL,
    ACTOR_NAME nvarchar(150) NULL,
    WORKSTATION_CODE varchar(100) NULL,
    EVENT_DATA nvarchar(max) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEEVENTS_CREATED DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_TBLPACKAGEEVENTS PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_TBLPACKAGEEVENTS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT FK_TBLPACKAGEEVENTS_PACKAGE FOREIGN KEY (PACKAGE_ID) REFERENCES dbo.TBLPACKAGEMASTER(PACKAGE_ID),
    CONSTRAINT FK_TBLPACKAGEEVENTS_ITEM FOREIGN KEY (PACKAGE_ITEM_ID) REFERENCES dbo.TBLPACKAGEITEMS(PACKAGE_ITEM_ID),
    CONSTRAINT CK_TBLPACKAGEEVENTS_RESULT CHECK (RESULT IS NULL OR RESULT IN ('SUCCESS','MATCHED','MISMATCHED','REJECTED','FAILED'))
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEEVENTS') AND name = N'IX_TBLPACKAGEEVENTS_WORKFLOW')
  CREATE INDEX IX_TBLPACKAGEEVENTS_WORKFLOW ON dbo.TBLPACKAGEEVENTS(WORKFLOW_ID, CREATED_AT DESC);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEEVENTS') AND name = N'IX_TBLPACKAGEEVENTS_PACKAGE')
  CREATE INDEX IX_TBLPACKAGEEVENTS_PACKAGE ON dbo.TBLPACKAGEEVENTS(PACKAGE_ID, CREATED_AT DESC) WHERE PACKAGE_ID IS NOT NULL;
GO

-- ===== Source: 005_enable_realtime_sync.sql =====

-- Install on the intended database. No patient/prescription data is rewritten.
SET XACT_ABORT ON;
IF EXISTS (
 SELECT 1 FROM (VALUES (N'TBLORX'),(N'TBLORXITEMS'),(N'TBLPATIENT'),(N'TBLMEDITEMSINFO'),(N'TBLDOCTOR'),(N'TBLDEPT'),(N'TBLWORKFLOWMASTER'),(N'TBLPACKAGEPRESCRIPTIONS'),(N'TBLPACKAGEMASTER'),(N'TBLPACKAGEITEMS')) required(name)
 WHERE OBJECT_ID(N'dbo.'+required.name,N'U') IS NULL
 OR NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.'+required.name) AND is_primary_key=1)
) THROW 51000, 'Realtime requires all source/workflow tables and their existing primary keys.', 1;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_databases WHERE database_id=DB_ID())
BEGIN
 IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE class=0 AND name=N'JurapornRealtimeEnabledCT')
  EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT', @value=1;
 DECLARE @ct nvarchar(max)=N'ALTER DATABASE '+QUOTENAME(DB_NAME())+N' SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 7 DAYS, AUTO_CLEANUP = ON)';
 EXEC sys.sp_executesql @ct;
END;
IF (SELECT snapshot_isolation_state FROM sys.databases WHERE database_id=DB_ID())=0
BEGIN
 IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE class=0 AND name=N'JurapornRealtimeEnabledSnapshot')
  EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledSnapshot', @value=1;
 DECLARE @snapshot nvarchar(max)=N'ALTER DATABASE '+QUOTENAME(DB_NAME())+N' SET ALLOW_SNAPSHOT_ISOLATION ON';
 EXEC sys.sp_executesql @snapshot;
END;
GO
IF OBJECT_ID(N'dbo.TBLREALTIMEINVALIDATIONS',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.TBLREALTIMEINVALIDATIONS (
  SCOPE_TYPE varchar(16) NOT NULL,
  SCOPE_KEY nvarchar(100) NOT NULL,
  TOUCHED_AT datetime2(3) NOT NULL CONSTRAINT DF_REALTIME_TOUCHED DEFAULT SYSUTCDATETIME(),
  CONSTRAINT PK_TBLREALTIMEINVALIDATIONS PRIMARY KEY (SCOPE_TYPE,SCOPE_KEY),
  CONSTRAINT CK_REALTIME_SCOPE CHECK (SCOPE_TYPE IN ('PATIENT','MEDICINE','GLOBAL'))
 );
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeCreated',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLREALTIMEINVALIDATIONS';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLORX'))
BEGIN
 ALTER TABLE dbo.TBLORX ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLORX';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLORXITEMS'))
BEGIN
 ALTER TABLE dbo.TBLORXITEMS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLORXITEMS';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLPATIENT'))
BEGIN
 ALTER TABLE dbo.TBLPATIENT ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLPATIENT';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLMEDITEMSINFO'))
BEGIN
 ALTER TABLE dbo.TBLMEDITEMSINFO ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLMEDITEMSINFO';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLDOCTOR'))
BEGIN
 ALTER TABLE dbo.TBLDOCTOR ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLDOCTOR';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLDEPT'))
BEGIN
 ALTER TABLE dbo.TBLDEPT ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLDEPT';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLWORKFLOWMASTER'))
BEGIN
 ALTER TABLE dbo.TBLWORKFLOWMASTER ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLWORKFLOWMASTER';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEPRESCRIPTIONS'))
BEGIN
 ALTER TABLE dbo.TBLPACKAGEPRESCRIPTIONS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLPACKAGEPRESCRIPTIONS';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER'))
BEGIN
 ALTER TABLE dbo.TBLPACKAGEMASTER ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLPACKAGEMASTER';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEITEMS'))
BEGIN
 ALTER TABLE dbo.TBLPACKAGEITEMS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLPACKAGEITEMS';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLREALTIMEINVALIDATIONS'))
BEGIN
 ALTER TABLE dbo.TBLREALTIMEINVALIDATIONS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLREALTIMEINVALIDATIONS';
END;
GO
CREATE OR ALTER TRIGGER dbo.TR_TBLALLERGY_Realtime ON dbo.TBLALLERGY
AFTER INSERT, UPDATE, DELETE AS
BEGIN
 SET NOCOUNT ON;
 DECLARE @keys TABLE (code nvarchar(100) NOT NULL PRIMARY KEY);
 INSERT INTO @keys(code)
 SELECT DISTINCT LTRIM(RTRIM(CONVERT(nvarchar(100),code)))
 FROM (SELECT HN AS code FROM inserted UNION SELECT HN FROM deleted) changed
 WHERE NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(100),code))),N'') IS NOT NULL;
 -- Range locks make the two-statement upsert safe for concurrent writers.
 UPDATE target WITH (UPDLOCK,SERIALIZABLE)
 SET TOUCHED_AT=SYSUTCDATETIME()
 FROM dbo.TBLREALTIMEINVALIDATIONS target JOIN @keys k ON target.SCOPE_KEY=k.code
 WHERE target.SCOPE_TYPE='PATIENT';
 INSERT INTO dbo.TBLREALTIMEINVALIDATIONS(SCOPE_TYPE,SCOPE_KEY)
 SELECT 'PATIENT',k.code FROM @keys k
 WHERE NOT EXISTS (SELECT 1 FROM dbo.TBLREALTIMEINVALIDATIONS WITH (UPDLOCK,SERIALIZABLE)
  WHERE SCOPE_TYPE='PATIENT' AND SCOPE_KEY=k.code);
END;
GO
CREATE OR ALTER TRIGGER dbo.TR_DrugInteraction_Realtime ON dbo.DrugInteraction
AFTER INSERT, UPDATE, DELETE AS
BEGIN
 SET NOCOUNT ON;
 DECLARE @keys TABLE (code nvarchar(100) NOT NULL PRIMARY KEY);
 INSERT INTO @keys(code)
 SELECT DISTINCT LTRIM(RTRIM(CONVERT(nvarchar(100),code)))
 FROM (SELECT StockCode AS code FROM inserted UNION SELECT WithStockCode FROM inserted UNION SELECT StockCode FROM deleted UNION SELECT WithStockCode FROM deleted) changed
 WHERE NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(100),code))),N'') IS NOT NULL;
 -- Range locks make the two-statement upsert safe for concurrent writers.
 UPDATE target WITH (UPDLOCK,SERIALIZABLE)
 SET TOUCHED_AT=SYSUTCDATETIME()
 FROM dbo.TBLREALTIMEINVALIDATIONS target JOIN @keys k ON target.SCOPE_KEY=k.code
 WHERE target.SCOPE_TYPE='MEDICINE';
 INSERT INTO dbo.TBLREALTIMEINVALIDATIONS(SCOPE_TYPE,SCOPE_KEY)
 SELECT 'MEDICINE',k.code FROM @keys k
 WHERE NOT EXISTS (SELECT 1 FROM dbo.TBLREALTIMEINVALIDATIONS WITH (UPDLOCK,SERIALIZABLE)
  WHERE SCOPE_TYPE='MEDICINE' AND SCOPE_KEY=k.code);
END;
GO

-- ===== Source: 003_validate_package_workflow.sql =====

SET NOCOUNT ON;

IF SCHEMA_ID(N'workflow') IS NOT NULL
  THROW 51000, 'Legacy workflow schema still exists.', 1;

IF OBJECT_ID(N'dbo.TBLORX', N'U') IS NULL
  THROW 51000, 'Source table dbo.TBLORX was not found.', 1;
IF OBJECT_ID(N'dbo.TBLORXITEMS', N'U') IS NULL
  THROW 51000, 'Source table dbo.TBLORXITEMS was not found.', 1;

IF COL_LENGTH(N'dbo.TBLORXITEMS', N'VISITDATETIME') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.VISITDATETIME was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'VISITNUMBER') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.VISITNUMBER was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'PRESCRIPTIONNUMBER') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.PRESCRIPTIONNUMBER was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'MEDICINECODE') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.MEDICINECODE was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'ITEMSEQ') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.ITEMSEQ was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'IS_DELETED') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.IS_DELETED was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'CANCELSTATUS') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.CANCELSTATUS was not found.', 1;

IF OBJECT_ID(N'dbo.TBLWORKFLOWMASTER', N'U') IS NULL
  THROW 51000, 'dbo.TBLWORKFLOWMASTER was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEPRESCRIPTIONS', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEPRESCRIPTIONS was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEMASTER', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEMASTER was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEITEMS', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEITEMS was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEEVENTS', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEEVENTS was not created.', 1;

IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_DRAFT') IS NULL
  THROW 51000, 'dbo.TBLWORKFLOWMASTER.VERIFY_NOTE_DRAFT was not created.', 1;
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_AT') IS NULL
  THROW 51000, 'dbo.TBLWORKFLOWMASTER.VERIFY_NOTE_UPDATED_AT was not created.', 1;
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_BY') IS NULL
  THROW 51000, 'dbo.TBLWORKFLOWMASTER.VERIFY_NOTE_UPDATED_BY was not created.', 1;
GO

-- ===== Source: 006_validate_realtime_sync.sql =====

-- Read-only deployment checks; all tracked tables and both triggers must be enabled.
SELECT DB_NAME() AS DATABASE_NAME, snapshot_isolation_state_desc FROM sys.databases WHERE database_id=DB_ID();
SELECT retention_period,retention_period_units_desc,is_auto_cleanup_on FROM sys.change_tracking_databases WHERE database_id=DB_ID();
SELECT t.name,ct.is_track_columns_updated_on,CHANGE_TRACKING_MIN_VALID_VERSION(t.object_id) AS MIN_VALID_VERSION
FROM sys.tables t LEFT JOIN sys.change_tracking_tables ct ON ct.object_id=t.object_id
WHERE t.name IN ('TBLORX','TBLORXITEMS','TBLPATIENT','TBLMEDITEMSINFO','TBLDOCTOR','TBLDEPT','TBLWORKFLOWMASTER','TBLPACKAGEPRESCRIPTIONS','TBLPACKAGEMASTER','TBLPACKAGEITEMS','TBLREALTIMEINVALIDATIONS');
SELECT name,is_disabled FROM sys.triggers WHERE name IN ('TR_TBLALLERGY_Realtime','TR_DrugInteraction_Realtime');
SELECT CHANGE_TRACKING_CURRENT_VERSION() AS CURRENT_VERSION;
IF (SELECT COUNT(*) FROM sys.change_tracking_tables WHERE object_id IN (
 OBJECT_ID('dbo.TBLORX'),OBJECT_ID('dbo.TBLORXITEMS'),OBJECT_ID('dbo.TBLPATIENT'),OBJECT_ID('dbo.TBLMEDITEMSINFO'),
 OBJECT_ID('dbo.TBLDOCTOR'),OBJECT_ID('dbo.TBLDEPT'),OBJECT_ID('dbo.TBLWORKFLOWMASTER'),OBJECT_ID('dbo.TBLPACKAGEPRESCRIPTIONS'),
 OBJECT_ID('dbo.TBLPACKAGEMASTER'),OBJECT_ID('dbo.TBLPACKAGEITEMS'),OBJECT_ID('dbo.TBLREALTIMEINVALIDATIONS')) AND is_track_columns_updated_on=1)<>11
 THROW 51000,'Realtime tables or column tracking are not fully enabled.',1;
IF (SELECT COUNT(*) FROM sys.triggers WHERE name IN ('TR_TBLALLERGY_Realtime','TR_DrugInteraction_Realtime') AND is_disabled=0)<>2
 THROW 51000,'Realtime clinical alert triggers are not fully enabled.',1;
IF (SELECT snapshot_isolation_state FROM sys.databases WHERE database_id=DB_ID())<>1
 THROW 51000,'Snapshot isolation is not enabled.',1;
GO

PRINT 'JurapornWeb full-stack database installation and validation completed successfully.';

GO

