/*
  JurapornWeb Full-stack Database Installer
  GENERATED FILE - DO NOT EDIT DIRECTLY

  Regenerate with: npm run db:bundle
  Included: 001 package workflow, 005 realtime, 009 dispensing, 010 drug labels, 003/006 validation
  Excluded: 002 destructive cleanup, 004 test seed, 007 rollback, 008 already folded into 001

  Prerequisite: select an existing copied hospital database containing the source tables.
  This file is intentionally rerunnable and does not insert test data.
*/

-- ===== Preflight: no database changes occur before this batch passes =====

SET NOCOUNT ON;
SET XACT_ABORT ON;

IF DB_NAME() IN (N'master', N'model', N'msdb', N'tempdb')
  THROW 51000, 'Choose the copied hospital application database before installing JurapornWeb.', 1;

IF SCHEMA_ID(N'workflow') IS NOT NULL
  THROW 51000, 'Legacy schema [workflow] exists. Back up and review 002_drop_legacy_workflow_schema.sql separately before installation.', 1;

IF HAS_PERMS_BY_NAME(DB_NAME(), 'DATABASE', 'ALTER') <> 1
  THROW 51000, 'Installer account requires ALTER permission on the selected database.', 1;
IF HAS_PERMS_BY_NAME(DB_NAME(), 'DATABASE', 'CREATE TABLE') <> 1
  THROW 51000, 'Installer account requires CREATE TABLE permission on the selected database.', 1;
IF HAS_PERMS_BY_NAME(N'dbo', 'SCHEMA', 'ALTER') <> 1
  THROW 51000, 'Installer account requires ALTER permission on schema dbo.', 1;

DECLARE @RequiredTables TABLE (TABLE_NAME sysname NOT NULL PRIMARY KEY);
INSERT INTO @RequiredTables (TABLE_NAME)
VALUES
  (N'TBLORX'), (N'TBLORXITEMS'), (N'TBLPATIENT'), (N'TBLMEDITEMSINFO'),
  (N'TBLDOCTOR'), (N'TBLDEPT'), (N'TBLALLERGY'), (N'DrugInteraction');

DECLARE @MissingTable sysname = (
  SELECT TOP (1) required.TABLE_NAME
  FROM @RequiredTables AS required
  WHERE OBJECT_ID(N'dbo.' + required.TABLE_NAME, N'U') IS NULL
  ORDER BY required.TABLE_NAME
);
IF @MissingTable IS NOT NULL
  THROW 51000, 'A required source table is missing. This installer requires the existing hospital database (TBLORX, TBLORXITEMS, patient, allergy and reference tables).', 1;

DECLARE @TrackedSourceTables TABLE (TABLE_NAME sysname NOT NULL PRIMARY KEY);
INSERT INTO @TrackedSourceTables (TABLE_NAME)
VALUES (N'TBLORX'), (N'TBLORXITEMS'), (N'TBLPATIENT'), (N'TBLMEDITEMSINFO'), (N'TBLDOCTOR'), (N'TBLDEPT');

DECLARE @MissingPrimaryKey sysname = (
  SELECT TOP (1) tracked.TABLE_NAME
  FROM @TrackedSourceTables AS tracked
  WHERE NOT EXISTS (
    SELECT 1
    FROM sys.indexes AS index_info
    WHERE index_info.object_id = OBJECT_ID(N'dbo.' + tracked.TABLE_NAME)
      AND index_info.is_primary_key = 1
  )
  ORDER BY tracked.TABLE_NAME
);
IF @MissingPrimaryKey IS NOT NULL
  THROW 51000, 'A source table required by Change Tracking has no Primary Key. No key is created automatically; ask the DBA to review the source schema.', 1;

DECLARE @RequiredColumns TABLE (TABLE_NAME sysname NOT NULL, COLUMN_NAME sysname NOT NULL, PRIMARY KEY (TABLE_NAME, COLUMN_NAME));
INSERT INTO @RequiredColumns (TABLE_NAME, COLUMN_NAME)
VALUES
  (N'TBLORX', N'VISITDATETIME'), (N'TBLORX', N'VISITNUMBER'),
  (N'TBLORX', N'PRESCRIPTIONNUMBER'), (N'TBLORX', N'PATIENTID'),
  (N'TBLORXITEMS', N'VISITDATETIME'), (N'TBLORXITEMS', N'VISITNUMBER'),
  (N'TBLORXITEMS', N'PRESCRIPTIONNUMBER'), (N'TBLORXITEMS', N'MEDICINECODE'),
  (N'TBLORXITEMS', N'ITEMSEQ'), (N'TBLORXITEMS', N'IS_DELETED'),
  (N'TBLORXITEMS', N'CANCELSTATUS'), (N'TBLPATIENT', N'PATIENTID'),
  (N'TBLMEDITEMSINFO', N'MEDICINECODE'), (N'TBLDOCTOR', N'DOCTORCODE'),
  (N'TBLDEPT', N'DEPTCODE'), (N'TBLALLERGY', N'HN'),
  (N'TBLALLERGY', N'MEDICINECODE'), (N'DrugInteraction', N'StockCode'),
  (N'DrugInteraction', N'WithStockCode');

DECLARE @MissingColumn nvarchar(260) = (
  SELECT TOP (1) required.TABLE_NAME + N'.' + required.COLUMN_NAME
  FROM @RequiredColumns AS required
  WHERE COL_LENGTH(N'dbo.' + required.TABLE_NAME, required.COLUMN_NAME) IS NULL
  ORDER BY required.TABLE_NAME, required.COLUMN_NAME
);
IF @MissingColumn IS NOT NULL
  THROW 51000, 'A required source column is missing. The copied hospital database is not compatible with this JurapornWeb installer.', 1;

PRINT 'JurapornWeb preflight passed for database [' + DB_NAME() + '].';
GO

-- ===== Source: 001_create_package_workflow_schema.sql =====

SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.TBLWORKFLOWMASTER', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLWORKFLOWMASTER (
    WORKFLOW_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_ID DEFAULT NEWSEQUENTIALID(),
    WORKFLOW_PUBLIC_ID varchar(48) NOT NULL,
    VISITDATETIME date NOT NULL,
    VISITNUMBER varchar(10) NOT NULL,
    PATIENTID varchar(15) NULL,
    PATIENT_NAME nvarchar(200) NULL,
    WORKFLOW_RUN_NO int NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_RUN DEFAULT 1,
    CASE_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_STATUS DEFAULT 'VERIFY',
    IS_ACTIVE bit NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_ACTIVE DEFAULT 1,
    QUEUE_NO int NULL,
    BLOCK_REASON_CODE varchar(80) NULL,
    BLOCK_REASON_TEXT nvarchar(1000) NULL,
    PAYMENT_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_PAYMENT DEFAULT 'BYPASSED',
    PAYMENT_REFERENCE varchar(100) NULL,
    PAID_AT datetime2(3) NULL,
    PAYMENT_UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_PAYMENT_AT DEFAULT SYSUTCDATETIME(),
    VERIFY_LOCK_TOKEN uniqueidentifier NULL,
    VERIFY_LOCK_SESSION varchar(100) NULL,
    VERIFY_LOCK_OWNER nvarchar(150) NULL,
    VERIFY_LOCK_WORKSTATION varchar(100) NULL,
    VERIFY_LOCKED_AT datetime2(3) NULL,
    VERIFY_LOCK_HEARTBEAT_AT datetime2(3) NULL,
    VERIFY_LOCK_EXPIRES_AT datetime2(3) NULL,
    VERIFY_NOTE_DRAFT nvarchar(1000) NULL,
    VERIFY_NOTE_UPDATED_AT datetime2(3) NULL,
    VERIFY_NOTE_UPDATED_BY nvarchar(150) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLWORKFLOWMASTER_UPDATED DEFAULT SYSUTCDATETIME(),
    COMPLETED_AT datetime2(3) NULL,
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLWORKFLOWMASTER PRIMARY KEY (WORKFLOW_ID),
    CONSTRAINT CK_TBLWORKFLOWMASTER_STATUS CHECK (CASE_STATUS IN ('VERIFY','PENDING','IN_PROGRESS','COMPLETE','BLOCKED','CANCELLED')),
    CONSTRAINT CK_TBLWORKFLOWMASTER_PAYMENT CHECK (PAYMENT_STATUS IN ('WAITING','PAID','FAILED','BYPASSED'))
  );
END;
GO

-- Keep the current installer idempotent for databases created by an older 001.
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_DRAFT') IS NULL
  ALTER TABLE dbo.TBLWORKFLOWMASTER ADD VERIFY_NOTE_DRAFT nvarchar(1000) NULL;
GO
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_AT') IS NULL
  ALTER TABLE dbo.TBLWORKFLOWMASTER ADD VERIFY_NOTE_UPDATED_AT datetime2(3) NULL;
GO
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_BY') IS NULL
  ALTER TABLE dbo.TBLWORKFLOWMASTER ADD VERIFY_NOTE_UPDATED_BY nvarchar(150) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'UX_TBLWORKFLOWMASTER_PUBLIC')
  CREATE UNIQUE INDEX UX_TBLWORKFLOWMASTER_PUBLIC ON dbo.TBLWORKFLOWMASTER(WORKFLOW_PUBLIC_ID);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'UX_TBLWORKFLOWMASTER_RUN')
  CREATE UNIQUE INDEX UX_TBLWORKFLOWMASTER_RUN ON dbo.TBLWORKFLOWMASTER(VISITDATETIME, VISITNUMBER, WORKFLOW_RUN_NO);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'UX_TBLWORKFLOWMASTER_ACTIVE_VISIT')
  CREATE UNIQUE INDEX UX_TBLWORKFLOWMASTER_ACTIVE_VISIT ON dbo.TBLWORKFLOWMASTER(VISITDATETIME, VISITNUMBER) WHERE IS_ACTIVE = 1;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLWORKFLOWMASTER') AND name = N'IX_TBLWORKFLOWMASTER_QUEUE')
  CREATE INDEX IX_TBLWORKFLOWMASTER_QUEUE ON dbo.TBLWORKFLOWMASTER(CASE_STATUS, VISITDATETIME, IS_ACTIVE) INCLUDE (VISITNUMBER, PATIENTID, QUEUE_NO);
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEPRESCRIPTIONS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEPRESCRIPTIONS (
    PACKAGE_PRESCRIPTION_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_ID DEFAULT NEWSEQUENTIALID(),
    WORKFLOW_ID uniqueidentifier NOT NULL,
    PRESCRIPTIONNUMBER varchar(16) NOT NULL,
    VERIFY_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_STATUS DEFAULT 'WAITING',
    VERIFIED_BY nvarchar(150) NULL,
    VERIFIED_AT datetime2(3) NULL,
    SOURCE_HASH varchar(64) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEPRESCRIPTIONS_UPDATED DEFAULT SYSUTCDATETIME(),
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLPACKAGEPRESCRIPTIONS PRIMARY KEY (PACKAGE_PRESCRIPTION_ID),
    CONSTRAINT FK_TBLPACKAGEPRESCRIPTIONS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT UQ_TBLPACKAGEPRESCRIPTIONS_WORKFLOW_PN UNIQUE (WORKFLOW_ID, PRESCRIPTIONNUMBER),
    CONSTRAINT CK_TBLPACKAGEPRESCRIPTIONS_STATUS CHECK (VERIFY_STATUS IN ('WAITING','VERIFIED_WAITING','PARTIAL','PACKAGED','SOURCE_CHANGED'))
  );
END;
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEMASTER', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEMASTER (
    PACKAGE_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_ID DEFAULT NEWSEQUENTIALID(),
    WORKFLOW_ID uniqueidentifier NOT NULL,
    PACKAGE_NUMBER varchar(60) NOT NULL,
    BATCH_NO int NOT NULL,
    PACKAGE_PRIORITY varchar(16) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_PRIORITY DEFAULT 'NORMAL',
    PAGE_NOW varchar(32) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_PAGE DEFAULT 'PICKING',
    PACKAGE_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_STATUS DEFAULT 'ACTIVE',
    IS_ACTIVE bit NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_ACTIVE DEFAULT 1,
    VERIFY_NOTE nvarchar(1000) NULL,
    IDEMPOTENCY_KEY varchar(100) NOT NULL,
    VERIFIED_BY nvarchar(150) NULL,
    VERIFY_COMPLETED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_VERIFY_AT DEFAULT SYSUTCDATETIME(),
    PICKED_BY nvarchar(150) NULL,
    PICKING_COMPLETED_AT datetime2(3) NULL,
    MATCHED_BY nvarchar(150) NULL,
    MATCHING_COMPLETED_AT datetime2(3) NULL,
    CHECKED_BY nvarchar(150) NULL,
    CHECKING_COMPLETED_AT datetime2(3) NULL,
    DISPENSED_BY nvarchar(150) NULL,
    DISPENSING_COMPLETED_AT datetime2(3) NULL,
    DISPENSING_PICKUP_STATUS varchar(24) NULL,
    CALL_COUNT int NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_CALL_COUNT DEFAULT 0,
    LAST_CALLED_AT datetime2(3) NULL,
    RECEIVED_AT datetime2(3) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEMASTER_UPDATED DEFAULT SYSUTCDATETIME(),
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLPACKAGEMASTER PRIMARY KEY (PACKAGE_ID),
    CONSTRAINT FK_TBLPACKAGEMASTER_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT UQ_TBLPACKAGEMASTER_NUMBER UNIQUE (PACKAGE_NUMBER),
    CONSTRAINT UQ_TBLPACKAGEMASTER_BATCH UNIQUE (WORKFLOW_ID, BATCH_NO),
    CONSTRAINT UQ_TBLPACKAGEMASTER_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CK_TBLPACKAGEMASTER_PRIORITY CHECK (PACKAGE_PRIORITY IN ('URGENT','NORMAL')),
    CONSTRAINT CK_TBLPACKAGEMASTER_PAGE CHECK (PAGE_NOW IN ('PICKING','MATCHING','CHECKING','AWAITING_DISPENSING','DISPENSING','COMPLETE')),
    CONSTRAINT CK_TBLPACKAGEMASTER_STATUS CHECK (PACKAGE_STATUS IN ('ACTIVE','COMPLETED','BLOCKED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEMASTER_PICKUP CHECK (DISPENSING_PICKUP_STATUS IS NULL OR DISPENSING_PICKUP_STATUS IN ('WAITING_CALL','CALLED_WAITING','RECEIVED'))
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name = N'UX_TBLPACKAGEMASTER_ACTIVE_WORKFLOW')
  CREATE UNIQUE INDEX UX_TBLPACKAGEMASTER_ACTIVE_WORKFLOW ON dbo.TBLPACKAGEMASTER(WORKFLOW_ID) WHERE IS_ACTIVE = 1;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name = N'IX_TBLPACKAGEMASTER_PAGE')
  CREATE INDEX IX_TBLPACKAGEMASTER_PAGE ON dbo.TBLPACKAGEMASTER(PAGE_NOW, IS_ACTIVE, UPDATED_AT DESC) INCLUDE (WORKFLOW_ID, PACKAGE_NUMBER, PACKAGE_PRIORITY);
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEITEMS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEITEMS (
    PACKAGE_ITEM_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_ID DEFAULT NEWSEQUENTIALID(),
    PACKAGE_ID uniqueidentifier NOT NULL,
    WORKFLOW_ID uniqueidentifier NOT NULL,
    VISITDATETIME date NOT NULL,
    VISITNUMBER varchar(10) NOT NULL,
    PRESCRIPTIONNUMBER varchar(16) NOT NULL,
    MEDICINECODE varchar(30) NOT NULL,
    ITEMSEQ int NOT NULL,
    SOURCE_CREATED_AT datetime2(3) NULL,
    SOURCE_HASH varchar(64) NULL,
    SOURCE_URGENCY_CODE varchar(40) NULL,
    COMMERCIALNAME nvarchar(300) NULL,
    ORDERQTY decimal(18,2) NULL,
    ORDERUNITCODE varchar(32) NULL,
    DOSEMEMO_TH nvarchar(max) NULL,
    PICKING_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_PICKING DEFAULT 'WAITING',
    MATCHING_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_MATCHING DEFAULT 'WAITING',
    CHECKING_STATUS varchar(24) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_CHECKING DEFAULT 'WAITING',
    PICKED_BY nvarchar(150) NULL,
    PICKED_AT datetime2(3) NULL,
    MATCHED_BY nvarchar(150) NULL,
    MATCHED_AT datetime2(3) NULL,
    CHECKED_BY nvarchar(150) NULL,
    CHECKED_AT datetime2(3) NULL,
    LABEL_PUBLIC_ID varchar(60) NOT NULL,
    QR_TOKEN varchar(100) NOT NULL,
    LABEL_PAYLOAD nvarchar(max) NULL,
    LABEL_TEMPLATE_VERSION int NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_LABEL_VERSION DEFAULT 1,
    LABEL_STATUS varchar(32) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_LABEL_STATUS DEFAULT 'READY_TO_PRINT',
    PRINT_COUNT int NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_PRINT_COUNT DEFAULT 0,
    PRINTED_AT datetime2(3) NULL,
    LABEL_CHECKED_AT datetime2(3) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEITEMS_UPDATED DEFAULT SYSUTCDATETIME(),
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLPACKAGEITEMS PRIMARY KEY (PACKAGE_ITEM_ID),
    CONSTRAINT FK_TBLPACKAGEITEMS_PACKAGE FOREIGN KEY (PACKAGE_ID) REFERENCES dbo.TBLPACKAGEMASTER(PACKAGE_ID),
    CONSTRAINT FK_TBLPACKAGEITEMS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT UQ_TBLPACKAGEITEMS_SOURCE UNIQUE (WORKFLOW_ID, PRESCRIPTIONNUMBER, MEDICINECODE, ITEMSEQ),
    CONSTRAINT UQ_TBLPACKAGEITEMS_LABEL_PUBLIC UNIQUE (LABEL_PUBLIC_ID),
    CONSTRAINT UQ_TBLPACKAGEITEMS_QR UNIQUE (QR_TOKEN),
    CONSTRAINT CK_TBLPACKAGEITEMS_PICKING CHECK (PICKING_STATUS IN ('WAITING','COMPLETED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEITEMS_MATCHING CHECK (MATCHING_STATUS IN ('WAITING','COMPLETED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEITEMS_CHECKING CHECK (CHECKING_STATUS IN ('WAITING','COMPLETED','CANCELLED')),
    CONSTRAINT CK_TBLPACKAGEITEMS_LABEL_STATUS CHECK (LABEL_STATUS IN ('READY_TO_PRINT','PRINTED','CHECKED','VOIDED'))
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEITEMS') AND name = N'IX_TBLPACKAGEITEMS_PACKAGE')
  CREATE INDEX IX_TBLPACKAGEITEMS_PACKAGE ON dbo.TBLPACKAGEITEMS(PACKAGE_ID, PRESCRIPTIONNUMBER, ITEMSEQ);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEITEMS') AND name = N'IX_TBLPACKAGEITEMS_MEDICINE')
  CREATE INDEX IX_TBLPACKAGEITEMS_MEDICINE ON dbo.TBLPACKAGEITEMS(PACKAGE_ID, MEDICINECODE) INCLUDE (MATCHING_STATUS, CHECKING_STATUS, QR_TOKEN);
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEEVENTS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLPACKAGEEVENTS (
    EVENT_ID bigint IDENTITY(1,1) NOT NULL,
    WORKFLOW_ID uniqueidentifier NOT NULL,
    PACKAGE_ID uniqueidentifier NULL,
    PACKAGE_ITEM_ID uniqueidentifier NULL,
    EVENT_TYPE varchar(60) NOT NULL,
    FROM_PAGE varchar(32) NULL,
    TO_PAGE varchar(32) NULL,
    SCAN_TYPE varchar(40) NULL,
    SCANNED_VALUE varchar(200) NULL,
    EXPECTED_VALUE varchar(200) NULL,
    RESULT varchar(32) NULL,
    FAILURE_REASON nvarchar(1000) NULL,
    ACTOR_ID varchar(80) NULL,
    ACTOR_NAME nvarchar(150) NULL,
    WORKSTATION_CODE varchar(100) NULL,
    EVENT_DATA nvarchar(max) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLPACKAGEEVENTS_CREATED DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_TBLPACKAGEEVENTS PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_TBLPACKAGEEVENTS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES dbo.TBLWORKFLOWMASTER(WORKFLOW_ID),
    CONSTRAINT FK_TBLPACKAGEEVENTS_PACKAGE FOREIGN KEY (PACKAGE_ID) REFERENCES dbo.TBLPACKAGEMASTER(PACKAGE_ID),
    CONSTRAINT FK_TBLPACKAGEEVENTS_ITEM FOREIGN KEY (PACKAGE_ITEM_ID) REFERENCES dbo.TBLPACKAGEITEMS(PACKAGE_ITEM_ID),
    CONSTRAINT CK_TBLPACKAGEEVENTS_RESULT CHECK (RESULT IS NULL OR RESULT IN ('SUCCESS','MATCHED','MISMATCHED','REJECTED','FAILED'))
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEEVENTS') AND name = N'IX_TBLPACKAGEEVENTS_WORKFLOW')
  CREATE INDEX IX_TBLPACKAGEEVENTS_WORKFLOW ON dbo.TBLPACKAGEEVENTS(WORKFLOW_ID, CREATED_AT DESC);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TBLPACKAGEEVENTS') AND name = N'IX_TBLPACKAGEEVENTS_PACKAGE')
  CREATE INDEX IX_TBLPACKAGEEVENTS_PACKAGE ON dbo.TBLPACKAGEEVENTS(PACKAGE_ID, CREATED_AT DESC) WHERE PACKAGE_ID IS NOT NULL;
GO

-- ===== Source: 005_enable_realtime_sync.sql =====

-- Install on the intended database. No patient/prescription data is rewritten.
SET XACT_ABORT ON;
IF EXISTS (
 SELECT 1 FROM (VALUES (N'TBLORX'),(N'TBLORXITEMS'),(N'TBLPATIENT'),(N'TBLMEDITEMSINFO'),(N'TBLDOCTOR'),(N'TBLDEPT'),(N'TBLWORKFLOWMASTER'),(N'TBLPACKAGEPRESCRIPTIONS'),(N'TBLPACKAGEMASTER'),(N'TBLPACKAGEITEMS')) required(name)
 WHERE OBJECT_ID(N'dbo.'+required.name,N'U') IS NULL
 OR NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.'+required.name) AND is_primary_key=1)
) THROW 51000, 'Realtime requires all source/workflow tables and their existing primary keys.', 1;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_databases WHERE database_id=DB_ID())
BEGIN
 IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE class=0 AND name=N'JurapornRealtimeEnabledCT')
  EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT', @value=1;
 DECLARE @ct nvarchar(max)=N'ALTER DATABASE '+QUOTENAME(DB_NAME())+N' SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 7 DAYS, AUTO_CLEANUP = ON)';
 EXEC sys.sp_executesql @ct;
END;
IF (SELECT snapshot_isolation_state FROM sys.databases WHERE database_id=DB_ID())=0
BEGIN
 IF NOT EXISTS (SELECT 1 FROM sys.extended_properties WHERE class=0 AND name=N'JurapornRealtimeEnabledSnapshot')
  EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledSnapshot', @value=1;
 DECLARE @snapshot nvarchar(max)=N'ALTER DATABASE '+QUOTENAME(DB_NAME())+N' SET ALLOW_SNAPSHOT_ISOLATION ON';
 EXEC sys.sp_executesql @snapshot;
END;
GO
IF OBJECT_ID(N'dbo.TBLREALTIMEINVALIDATIONS',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.TBLREALTIMEINVALIDATIONS (
  SCOPE_TYPE varchar(16) NOT NULL,
  SCOPE_KEY nvarchar(100) NOT NULL,
  TOUCHED_AT datetime2(3) NOT NULL CONSTRAINT DF_REALTIME_TOUCHED DEFAULT SYSUTCDATETIME(),
  CONSTRAINT PK_TBLREALTIMEINVALIDATIONS PRIMARY KEY (SCOPE_TYPE,SCOPE_KEY),
  CONSTRAINT CK_REALTIME_SCOPE CHECK (SCOPE_TYPE IN ('PATIENT','MEDICINE','GLOBAL'))
 );
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeCreated',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLREALTIMEINVALIDATIONS';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLORX'))
BEGIN
 ALTER TABLE dbo.TBLORX ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLORX';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLORXITEMS'))
BEGIN
 ALTER TABLE dbo.TBLORXITEMS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLORXITEMS';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLPATIENT'))
BEGIN
 ALTER TABLE dbo.TBLPATIENT ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLPATIENT';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLMEDITEMSINFO'))
BEGIN
 ALTER TABLE dbo.TBLMEDITEMSINFO ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLMEDITEMSINFO';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLDOCTOR'))
BEGIN
 ALTER TABLE dbo.TBLDOCTOR ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLDOCTOR';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLDEPT'))
BEGIN
 ALTER TABLE dbo.TBLDEPT ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLDEPT';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLWORKFLOWMASTER'))
BEGIN
 ALTER TABLE dbo.TBLWORKFLOWMASTER ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLWORKFLOWMASTER';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEPRESCRIPTIONS'))
BEGIN
 ALTER TABLE dbo.TBLPACKAGEPRESCRIPTIONS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLPACKAGEPRESCRIPTIONS';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER'))
BEGIN
 ALTER TABLE dbo.TBLPACKAGEMASTER ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLPACKAGEMASTER';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEITEMS'))
BEGIN
 ALTER TABLE dbo.TBLPACKAGEITEMS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLPACKAGEITEMS';
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLREALTIMEINVALIDATIONS'))
BEGIN
 ALTER TABLE dbo.TBLREALTIMEINVALIDATIONS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
 EXEC sys.sp_addextendedproperty @name=N'JurapornRealtimeEnabledCT',@value=1,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'TBLREALTIMEINVALIDATIONS';
END;
GO
CREATE OR ALTER TRIGGER dbo.TR_TBLALLERGY_Realtime ON dbo.TBLALLERGY
AFTER INSERT, UPDATE, DELETE AS
BEGIN
 SET NOCOUNT ON;
 DECLARE @keys TABLE (code nvarchar(100) NOT NULL PRIMARY KEY);
 INSERT INTO @keys(code)
 SELECT DISTINCT LTRIM(RTRIM(CONVERT(nvarchar(100),code)))
 FROM (SELECT HN AS code FROM inserted UNION SELECT HN FROM deleted) changed
 WHERE NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(100),code))),N'') IS NOT NULL;
 -- Range locks make the two-statement upsert safe for concurrent writers.
 UPDATE target WITH (UPDLOCK,SERIALIZABLE)
 SET TOUCHED_AT=SYSUTCDATETIME()
 FROM dbo.TBLREALTIMEINVALIDATIONS target JOIN @keys k ON target.SCOPE_KEY=k.code
 WHERE target.SCOPE_TYPE='PATIENT';
 INSERT INTO dbo.TBLREALTIMEINVALIDATIONS(SCOPE_TYPE,SCOPE_KEY)
 SELECT 'PATIENT',k.code FROM @keys k
 WHERE NOT EXISTS (SELECT 1 FROM dbo.TBLREALTIMEINVALIDATIONS WITH (UPDLOCK,SERIALIZABLE)
  WHERE SCOPE_TYPE='PATIENT' AND SCOPE_KEY=k.code);
END;
GO
CREATE OR ALTER TRIGGER dbo.TR_DrugInteraction_Realtime ON dbo.DrugInteraction
AFTER INSERT, UPDATE, DELETE AS
BEGIN
 SET NOCOUNT ON;
 DECLARE @keys TABLE (code nvarchar(100) NOT NULL PRIMARY KEY);
 INSERT INTO @keys(code)
 SELECT DISTINCT LTRIM(RTRIM(CONVERT(nvarchar(100),code)))
 FROM (SELECT StockCode AS code FROM inserted UNION SELECT WithStockCode FROM inserted UNION SELECT StockCode FROM deleted UNION SELECT WithStockCode FROM deleted) changed
 WHERE NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(100),code))),N'') IS NOT NULL;
 -- Range locks make the two-statement upsert safe for concurrent writers.
 UPDATE target WITH (UPDLOCK,SERIALIZABLE)
 SET TOUCHED_AT=SYSUTCDATETIME()
 FROM dbo.TBLREALTIMEINVALIDATIONS target JOIN @keys k ON target.SCOPE_KEY=k.code
 WHERE target.SCOPE_TYPE='MEDICINE';
 INSERT INTO dbo.TBLREALTIMEINVALIDATIONS(SCOPE_TYPE,SCOPE_KEY)
 SELECT 'MEDICINE',k.code FROM @keys k
 WHERE NOT EXISTS (SELECT 1 FROM dbo.TBLREALTIMEINVALIDATIONS WITH (UPDLOCK,SERIALIZABLE)
  WHERE SCOPE_TYPE='MEDICINE' AND SCOPE_KEY=k.code);
END;
GO

-- ===== Source: 009_dispensing_queue.sql =====

SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.TBLHOSPITALQUEUESTEP', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLHOSPITALQUEUESTEP (
    VISIT_DATE date NOT NULL,
    VN varchar(50) NOT NULL,
    STEP_ID varchar(2) NOT NULL,
    FIRST_READY_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLHOSPITALQUEUESTEP_FIRST DEFAULT SYSUTCDATETIME(),
    LAST_RECEIVED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLHOSPITALQUEUESTEP_LAST DEFAULT SYSUTCDATETIME(),
    RECEIPT_COUNT int NOT NULL CONSTRAINT DF_TBLHOSPITALQUEUESTEP_COUNT DEFAULT 1,
    APPLIED_WORKFLOW_ID uniqueidentifier NULL,
    CONSTRAINT PK_TBLHOSPITALQUEUESTEP PRIMARY KEY (VISIT_DATE, VN),
    CONSTRAINT CK_TBLHOSPITALQUEUESTEP_STEP CHECK (STEP_ID = '04')
  );
END;
GO

IF OBJECT_ID(N'dbo.TBLDISPENSINGCHANNELCLAIMS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLDISPENSINGCHANNELCLAIMS (
    CLAIM_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLDISPENSINGCHANNELCLAIMS_ID DEFAULT NEWSEQUENTIALID(),
    CHANNEL_NO tinyint NOT NULL,
    CLAIM_TOKEN_HASH varbinary(32) NOT NULL,
    CLAIMED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLDISPENSINGCHANNELCLAIMS_AT DEFAULT SYSUTCDATETIME(),
    RELEASED_AT datetime2(3) NULL,
    RELEASE_REASON nvarchar(200) NULL,
    CONSTRAINT PK_TBLDISPENSINGCHANNELCLAIMS PRIMARY KEY (CLAIM_ID),
    CONSTRAINT CK_TBLDISPENSINGCHANNELCLAIMS_CHANNEL CHECK (CHANNEL_NO BETWEEN 1 AND 8)
  );
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TBLDISPENSINGCHANNELCLAIMS') AND name=N'UX_TBLDISPENSINGCHANNELCLAIMS_ACTIVE')
  CREATE UNIQUE INDEX UX_TBLDISPENSINGCHANNELCLAIMS_ACTIVE ON dbo.TBLDISPENSINGCHANNELCLAIMS(CHANNEL_NO) WHERE RELEASED_AT IS NULL;
GO

IF COL_LENGTH(N'dbo.TBLPACKAGEMASTER', N'DISPENSING_CHANNEL') IS NULL
  ALTER TABLE dbo.TBLPACKAGEMASTER ADD DISPENSING_CHANNEL tinyint NULL;
GO
IF COL_LENGTH(N'dbo.TBLPACKAGEMASTER', N'QUEUE_READY_AT') IS NULL
  ALTER TABLE dbo.TBLPACKAGEMASTER ADD QUEUE_READY_AT datetime2(3) NULL;
GO
IF COL_LENGTH(N'dbo.TBLPACKAGEMASTER', N'MISSED_AT') IS NULL
  ALTER TABLE dbo.TBLPACKAGEMASTER ADD MISSED_AT datetime2(3) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name=N'CK_TBLPACKAGEMASTER_DISPENSING_CHANNEL')
  ALTER TABLE dbo.TBLPACKAGEMASTER ADD CONSTRAINT CK_TBLPACKAGEMASTER_DISPENSING_CHANNEL CHECK (DISPENSING_CHANNEL IS NULL OR DISPENSING_CHANNEL BETWEEN 1 AND 8);
GO
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER')
  AND name=N'CK_TBLPACKAGEMASTER_PICKUP' AND definition NOT LIKE '%MISSED_CALL%')
  ALTER TABLE dbo.TBLPACKAGEMASTER DROP CONSTRAINT CK_TBLPACKAGEMASTER_PICKUP;
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER')
  AND name=N'CK_TBLPACKAGEMASTER_PICKUP')
  ALTER TABLE dbo.TBLPACKAGEMASTER WITH CHECK ADD CONSTRAINT CK_TBLPACKAGEMASTER_PICKUP
    CHECK (DISPENSING_PICKUP_STATUS IS NULL OR DISPENSING_PICKUP_STATUS IN ('WAITING_CALL','CALLED_WAITING','MISSED_CALL','RECEIVED'));
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name=N'IX_TBLPACKAGEMASTER_DISPENSING_QUEUE')
  CREATE INDEX IX_TBLPACKAGEMASTER_DISPENSING_QUEUE ON dbo.TBLPACKAGEMASTER(PAGE_NOW, DISPENSING_CHANNEL, QUEUE_READY_AT, PACKAGE_ID)
    INCLUDE (WORKFLOW_ID, DISPENSING_PICKUP_STATUS, CHECKING_COMPLETED_AT, RECEIVED_AT);
GO

IF COL_LENGTH(N'dbo.TBLPACKAGEEVENTS', N'ACTION_ID') IS NULL
  ALTER TABLE dbo.TBLPACKAGEEVENTS ADD ACTION_ID uniqueidentifier NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEEVENTS') AND name=N'UX_TBLPACKAGEEVENTS_ACTION_ID')
  CREATE UNIQUE INDEX UX_TBLPACKAGEEVENTS_ACTION_ID ON dbo.TBLPACKAGEEVENTS(ACTION_ID) WHERE ACTION_ID IS NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLHOSPITALQUEUESTEP'))
  ALTER TABLE dbo.TBLHOSPITALQUEUESTEP ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO
IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_tables WHERE object_id=OBJECT_ID(N'dbo.TBLDISPENSINGCHANNELCLAIMS'))
  ALTER TABLE dbo.TBLDISPENSINGCHANNELCLAIMS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

SELECT name FROM sys.tables WHERE name IN ('TBLHOSPITALQUEUESTEP','TBLDISPENSINGCHANNELCLAIMS');
SELECT name FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEMASTER') AND name IN ('DISPENSING_CHANNEL','QUEUE_READY_AT','MISSED_AT');
GO

-- ===== Source: 010_drug_label_templates.sql =====

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.TBLPACKAGEITEMS', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEITEMS is required before installing drug label templates.', 1;
GO

IF OBJECT_ID(N'dbo.TBLDRUGLABELTEMPLATES', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TBLDRUGLABELTEMPLATES (
    TEMPLATE_ID uniqueidentifier NOT NULL CONSTRAINT DF_TBLDRUGLABELTEMPLATES_ID DEFAULT NEWSEQUENTIALID(),
    TEMPLATE_NAME nvarchar(120) NOT NULL,
    VERSION_NO int NOT NULL,
    TEMPLATE_STATUS varchar(16) NOT NULL,
    WIDTH_MM decimal(8,2) NOT NULL,
    HEIGHT_MM decimal(8,2) NOT NULL,
    DEFINITION_JSON nvarchar(max) NOT NULL,
    LOGO_MIME_TYPE varchar(40) NULL,
    LOGO_DATA varbinary(max) NULL,
    UPDATED_BY nvarchar(150) NULL,
    CREATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLDRUGLABELTEMPLATES_CREATED DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2(3) NOT NULL CONSTRAINT DF_TBLDRUGLABELTEMPLATES_UPDATED DEFAULT SYSUTCDATETIME(),
    PUBLISHED_AT datetime2(3) NULL,
    ROW_VERSION rowversion NOT NULL,
    CONSTRAINT PK_TBLDRUGLABELTEMPLATES PRIMARY KEY (TEMPLATE_ID),
    CONSTRAINT CK_TBLDRUGLABELTEMPLATES_STATUS CHECK (TEMPLATE_STATUS IN ('DRAFT','ACTIVE','ARCHIVED')),
    CONSTRAINT CK_TBLDRUGLABELTEMPLATES_SIZE CHECK (WIDTH_MM BETWEEN 25.4 AND 304.8 AND HEIGHT_MM BETWEEN 25.4 AND 304.8),
    CONSTRAINT CK_TBLDRUGLABELTEMPLATES_JSON CHECK (ISJSON(DEFINITION_JSON) = 1)
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TBLDRUGLABELTEMPLATES') AND name=N'UX_TBLDRUGLABELTEMPLATES_ACTIVE')
  CREATE UNIQUE INDEX UX_TBLDRUGLABELTEMPLATES_ACTIVE ON dbo.TBLDRUGLABELTEMPLATES(TEMPLATE_STATUS) WHERE TEMPLATE_STATUS='ACTIVE';
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TBLDRUGLABELTEMPLATES') AND name=N'UX_TBLDRUGLABELTEMPLATES_DRAFT')
  CREATE UNIQUE INDEX UX_TBLDRUGLABELTEMPLATES_DRAFT ON dbo.TBLDRUGLABELTEMPLATES(TEMPLATE_STATUS) WHERE TEMPLATE_STATUS='DRAFT';
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TBLDRUGLABELTEMPLATES') AND name=N'IX_TBLDRUGLABELTEMPLATES_VERSION')
  CREATE INDEX IX_TBLDRUGLABELTEMPLATES_VERSION ON dbo.TBLDRUGLABELTEMPLATES(VERSION_NO DESC, CREATED_AT DESC);
GO

IF COL_LENGTH(N'dbo.TBLPACKAGEITEMS', N'LABEL_TEMPLATE_ID') IS NULL
  ALTER TABLE dbo.TBLPACKAGEITEMS ADD LABEL_TEMPLATE_ID uniqueidentifier NULL;
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys
  WHERE parent_object_id=OBJECT_ID(N'dbo.TBLPACKAGEITEMS')
    AND name=N'FK_TBLPACKAGEITEMS_LABEL_TEMPLATE'
)
  ALTER TABLE dbo.TBLPACKAGEITEMS WITH CHECK
    ADD CONSTRAINT FK_TBLPACKAGEITEMS_LABEL_TEMPLATE FOREIGN KEY (LABEL_TEMPLATE_ID)
    REFERENCES dbo.TBLDRUGLABELTEMPLATES(TEMPLATE_ID);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TBLPACKAGEITEMS') AND name=N'IX_TBLPACKAGEITEMS_LABEL_TEMPLATE')
  CREATE INDEX IX_TBLPACKAGEITEMS_LABEL_TEMPLATE ON dbo.TBLPACKAGEITEMS(LABEL_TEMPLATE_ID) WHERE LABEL_TEMPLATE_ID IS NOT NULL;
GO

DECLARE @DefaultDefinition nvarchar(max) = N'{
  "schemaVersion": 1,
  "elements": [
    {"id":"border","type":"box","xMm":1.5,"yMm":1.5,"widthMm":98.6,"heightMm":73.2,"zIndex":1,"borderColor":"#244487","borderWidth":0.5,"borderRadiusMm":3,"backgroundColor":"transparent"},
    {"id":"logo","type":"logo","xMm":5,"yMm":4,"widthMm":8,"heightMm":14,"zIndex":3,"fit":"contain","imageSrc":"/assets/juraporn-hospital-emblem.png"},
    {"id":"hospital_name","type":"text","text":"โรงพยาบาลจุฬาภรณ์","xMm":14,"yMm":6,"widthMm":24,"heightMm":5,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":8,"fontWeight":600,"textAlign":"left","color":"#244487"},
    {"id":"hospital_phone","type":"text","text":"Tel. 02 576 6000 หรือ 1118","xMm":14,"yMm":12,"widthMm":25,"heightMm":4,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":7,"fontWeight":500,"textAlign":"left","color":"#244487"},
    {"id":"patient_name","type":"field","dataKey":"patientName","xMm":40,"yMm":5,"widthMm":28,"heightMm":7,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":14,"fontWeight":700,"textAlign":"left","color":"#111827"},
    {"id":"visit_date","type":"field","dataKey":"visitDateTime","xMm":68,"yMm":5,"widthMm":24,"heightMm":6,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":9,"fontWeight":600,"textAlign":"right","color":"#111827"},
    {"id":"item_counter","type":"field","dataKey":"itemCounter","xMm":91,"yMm":3,"widthMm":7,"heightMm":5,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":10,"fontWeight":700,"textAlign":"right","color":"#111827"},
    {"id":"hn","type":"field","dataKey":"patientHn","prefix":"HN : ","xMm":40,"yMm":12,"widthMm":22,"heightMm":5,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":9,"fontWeight":600,"textAlign":"left","color":"#111827"},
    {"id":"vn","type":"field","dataKey":"visitVn","prefix":"VN : ","xMm":61,"yMm":12,"widthMm":17,"heightMm":5,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":9,"fontWeight":600,"textAlign":"left","color":"#111827"},
    {"id":"doctor","type":"field","dataKey":"doctorName","xMm":78,"yMm":12,"widthMm":20,"heightMm":5,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":9,"fontWeight":600,"textAlign":"right","color":"#111827"},
    {"id":"separator","type":"line","xMm":2,"yMm":20,"widthMm":97.6,"heightMm":0.4,"zIndex":2,"borderColor":"#111827","borderWidth":0.4,"lineStyle":"dashed"},
    {"id":"medicine","type":"field","dataKey":"medicineName","xMm":5,"yMm":24,"widthMm":70,"heightMm":8,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":16,"fontWeight":700,"textAlign":"left","color":"#111827"},
    {"id":"quantity","type":"field","dataKey":"quantity","prefix":"#","xMm":76,"yMm":24,"widthMm":20,"heightMm":7,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":13,"fontWeight":700,"textAlign":"right","color":"#111827"},
    {"id":"medicine_pronunciation","type":"field","dataKey":"medicinePronunciation","prefix":"[ ","suffix":" ]","xMm":8,"yMm":31,"widthMm":58,"heightMm":6,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":10,"fontWeight":600,"textAlign":"left","color":"#111827"},
    {"id":"dose","type":"field","dataKey":"doseMemo","xMm":5,"yMm":38,"widthMm":68,"heightMm":15,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":12,"fontWeight":500,"textAlign":"left","color":"#111827"},
    {"id":"indication","type":"field","dataKey":"indication","xMm":5,"yMm":52,"widthMm":65,"heightMm":6,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":12,"fontWeight":700,"textAlign":"left","color":"#111827"},
    {"id":"qr","type":"qr","dataKey":"qrToken","xMm":78,"yMm":32,"widthMm":15,"heightMm":15,"zIndex":3,"backgroundColor":"#ffffff"},
    {"id":"qr_caption","type":"text","text":"QR code ข้อมูลยา","xMm":76,"yMm":47,"widthMm":20,"heightMm":4,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":7,"fontWeight":500,"textAlign":"center","color":"#111827"},
    {"id":"expiry","type":"field","dataKey":"expiryDate","prefix":"วันหมดอายุ : ","xMm":70,"yMm":55,"widthMm":27,"heightMm":5,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":8,"fontWeight":500,"textAlign":"right","color":"#111827"},
    {"id":"footer_box","type":"box","xMm":1.5,"yMm":61,"widthMm":98.6,"heightMm":14.7,"zIndex":2,"borderColor":"#244487","borderWidth":0,"borderRadiusMm":3,"backgroundColor":"#244487"},
    {"id":"footer_instruction","type":"text","text":"ควรรับประทานยาตามแพทย์สั่งทุกวัน\n** โปรดแจ้งแพทย์หากเกิดอาการไอต่อเนื่องหลังใช้ยา**","xMm":22,"yMm":64,"widthMm":55,"heightMm":9,"zIndex":4,"fontFamily":"Sarabun","fontSizePt":9,"fontWeight":500,"textAlign":"center","color":"#ffffff"},
    {"id":"storage","type":"field","dataKey":"storageInstruction","xMm":78,"yMm":63,"widthMm":18,"heightMm":9,"zIndex":4,"fontFamily":"Sarabun","fontSizePt":9,"fontWeight":500,"textAlign":"center","color":"#ffffff","borderColor":"#ffffff","borderWidth":0.4}
  ]
}';

IF NOT EXISTS (SELECT 1 FROM dbo.TBLDRUGLABELTEMPLATES WHERE TEMPLATE_STATUS='ACTIVE')
  INSERT INTO dbo.TBLDRUGLABELTEMPLATES(TEMPLATE_NAME,VERSION_NO,TEMPLATE_STATUS,WIDTH_MM,HEIGHT_MM,DEFINITION_JSON,UPDATED_BY,PUBLISHED_AT)
  VALUES(N'ฉลากยามาตรฐาน 4x3 นิ้ว',1,'ACTIVE',101.60,76.20,@DefaultDefinition,N'System seed',SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM dbo.TBLDRUGLABELTEMPLATES WHERE TEMPLATE_STATUS='DRAFT')
  INSERT INTO dbo.TBLDRUGLABELTEMPLATES(TEMPLATE_NAME,VERSION_NO,TEMPLATE_STATUS,WIDTH_MM,HEIGHT_MM,DEFINITION_JSON,UPDATED_BY)
  SELECT TOP (1) TEMPLATE_NAME,VERSION_NO,'DRAFT',WIDTH_MM,HEIGHT_MM,DEFINITION_JSON,N'System seed'
  FROM dbo.TBLDRUGLABELTEMPLATES WHERE TEMPLATE_STATUS='ACTIVE' ORDER BY VERSION_NO DESC;
GO

/*
  Upgrade templates created by an older revision of migration 010 where the
  hospital name and telephone number were embedded in the logo image. This
  block is intentionally part of 010 so the same file works for both a fresh
  install and an existing database when it is run again.
*/
BEGIN TRANSACTION;

DECLARE
  @UpgradeTemplateId uniqueidentifier,
  @UpgradeTemplateName nvarchar(120),
  @UpgradeVersionNo int,
  @UpgradeTemplateStatus varchar(16),
  @UpgradeWidthMm decimal(8,2),
  @UpgradeHeightMm decimal(8,2),
  @UpgradeDefinition nvarchar(max),
  @UpgradeLogoMimeType varchar(40),
  @UpgradeLogoData varbinary(max),
  @UpgradeLogoIndex int,
  @UpgradeLogoPath nvarchar(100),
  @UpgradeNextVersion int;

DECLARE drug_label_header_cursor CURSOR LOCAL FAST_FORWARD FOR
  SELECT TEMPLATE_ID,TEMPLATE_NAME,VERSION_NO,TEMPLATE_STATUS,WIDTH_MM,HEIGHT_MM,
    DEFINITION_JSON,LOGO_MIME_TYPE,LOGO_DATA
  FROM dbo.TBLDRUGLABELTEMPLATES
  WHERE TEMPLATE_STATUS IN ('ACTIVE','DRAFT')
    AND EXISTS (
      SELECT 1 FROM OPENJSON(DEFINITION_JSON,'$.elements')
      WHERE JSON_VALUE(value,'$.id')='logo'
    )
    AND NOT EXISTS (
      SELECT 1 FROM OPENJSON(DEFINITION_JSON,'$.elements')
      WHERE JSON_VALUE(value,'$.id')='hospital_name'
    );

OPEN drug_label_header_cursor;
FETCH NEXT FROM drug_label_header_cursor INTO
  @UpgradeTemplateId,@UpgradeTemplateName,@UpgradeVersionNo,@UpgradeTemplateStatus,
  @UpgradeWidthMm,@UpgradeHeightMm,@UpgradeDefinition,@UpgradeLogoMimeType,@UpgradeLogoData;

WHILE @@FETCH_STATUS = 0
BEGIN
  SET @UpgradeLogoIndex = NULL;
  SELECT TOP (1) @UpgradeLogoIndex=TRY_CONVERT(int,[key])
  FROM OPENJSON(@UpgradeDefinition,'$.elements')
  WHERE JSON_VALUE(value,'$.id')='logo';

  IF @UpgradeLogoIndex IS NOT NULL
  BEGIN
    SET @UpgradeLogoPath = CONCAT('$.elements[',@UpgradeLogoIndex,']');
    SET @UpgradeDefinition = JSON_MODIFY(@UpgradeDefinition,CONCAT(@UpgradeLogoPath,'.xMm'),CONVERT(decimal(8,2),5));
    SET @UpgradeDefinition = JSON_MODIFY(@UpgradeDefinition,CONCAT(@UpgradeLogoPath,'.yMm'),CONVERT(decimal(8,2),4));
    SET @UpgradeDefinition = JSON_MODIFY(@UpgradeDefinition,CONCAT(@UpgradeLogoPath,'.widthMm'),CONVERT(decimal(8,2),8));
    SET @UpgradeDefinition = JSON_MODIFY(@UpgradeDefinition,CONCAT(@UpgradeLogoPath,'.heightMm'),CONVERT(decimal(8,2),14));
    SET @UpgradeDefinition = JSON_MODIFY(@UpgradeDefinition,CONCAT(@UpgradeLogoPath,'.imageSrc'),N'/assets/juraporn-hospital-emblem.png');
    SET @UpgradeDefinition = JSON_MODIFY(@UpgradeDefinition,'append $.elements',JSON_QUERY(N'{"id":"hospital_name","type":"text","text":"โรงพยาบาลจุฬาภรณ์","xMm":14,"yMm":6,"widthMm":24,"heightMm":5,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":8,"fontWeight":600,"textAlign":"left","color":"#244487"}'));
    SET @UpgradeDefinition = JSON_MODIFY(@UpgradeDefinition,'append $.elements',JSON_QUERY(N'{"id":"hospital_phone","type":"text","text":"Tel. 02 576 6000 หรือ 1118","xMm":14,"yMm":12,"widthMm":25,"heightMm":4,"zIndex":3,"fontFamily":"Sarabun","fontSizePt":7,"fontWeight":500,"textAlign":"left","color":"#244487"}'));

    IF @UpgradeTemplateStatus='ACTIVE' AND EXISTS (
      SELECT 1 FROM dbo.TBLPACKAGEITEMS WHERE LABEL_TEMPLATE_ID=@UpgradeTemplateId
    )
    BEGIN
      SELECT @UpgradeNextVersion=ISNULL(MAX(VERSION_NO),0)+1
      FROM dbo.TBLDRUGLABELTEMPLATES WITH (UPDLOCK,HOLDLOCK);

      UPDATE dbo.TBLDRUGLABELTEMPLATES
      SET TEMPLATE_STATUS='ARCHIVED',UPDATED_AT=SYSUTCDATETIME()
      WHERE TEMPLATE_ID=@UpgradeTemplateId;

      INSERT INTO dbo.TBLDRUGLABELTEMPLATES(
        TEMPLATE_NAME,VERSION_NO,TEMPLATE_STATUS,WIDTH_MM,HEIGHT_MM,DEFINITION_JSON,
        LOGO_MIME_TYPE,LOGO_DATA,UPDATED_BY,PUBLISHED_AT
      ) VALUES (
        @UpgradeTemplateName,@UpgradeNextVersion,'ACTIVE',@UpgradeWidthMm,@UpgradeHeightMm,
        @UpgradeDefinition,@UpgradeLogoMimeType,@UpgradeLogoData,N'System migration 010',SYSUTCDATETIME()
      );
    END
    ELSE
    BEGIN
      UPDATE dbo.TBLDRUGLABELTEMPLATES
      SET DEFINITION_JSON=@UpgradeDefinition,UPDATED_BY=N'System migration 010',UPDATED_AT=SYSUTCDATETIME()
      WHERE TEMPLATE_ID=@UpgradeTemplateId;
    END
  END

  FETCH NEXT FROM drug_label_header_cursor INTO
    @UpgradeTemplateId,@UpgradeTemplateName,@UpgradeVersionNo,@UpgradeTemplateStatus,
    @UpgradeWidthMm,@UpgradeHeightMm,@UpgradeDefinition,@UpgradeLogoMimeType,@UpgradeLogoData;
END

CLOSE drug_label_header_cursor;
DEALLOCATE drug_label_header_cursor;

COMMIT TRANSACTION;
GO

IF OBJECT_ID(N'dbo.TBLDRUGLABELTEMPLATES', N'U') IS NULL
  THROW 51000, 'dbo.TBLDRUGLABELTEMPLATES was not created.', 1;
IF COL_LENGTH(N'dbo.TBLPACKAGEITEMS', N'LABEL_TEMPLATE_ID') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEITEMS.LABEL_TEMPLATE_ID was not created.', 1;
IF (SELECT COUNT(*) FROM dbo.TBLDRUGLABELTEMPLATES WHERE TEMPLATE_STATUS='ACTIVE') <> 1
  THROW 51000, 'Exactly one ACTIVE drug label template is required.', 1;
IF (SELECT COUNT(*) FROM dbo.TBLDRUGLABELTEMPLATES WHERE TEMPLATE_STATUS='DRAFT') <> 1
  THROW 51000, 'Exactly one DRAFT drug label template is required.', 1;
IF EXISTS (
  SELECT 1
  FROM dbo.TBLDRUGLABELTEMPLATES
  WHERE TEMPLATE_STATUS IN ('ACTIVE','DRAFT')
    AND NOT EXISTS (
      SELECT 1 FROM OPENJSON(DEFINITION_JSON,'$.elements')
      WHERE JSON_VALUE(value,'$.id')='hospital_name'
    )
)
  THROW 51000, 'The hospital-name text element was not installed.', 1;
GO

SELECT TEMPLATE_ID,TEMPLATE_NAME,VERSION_NO,TEMPLATE_STATUS,WIDTH_MM,HEIGHT_MM,UPDATED_AT,PUBLISHED_AT
FROM dbo.TBLDRUGLABELTEMPLATES ORDER BY TEMPLATE_STATUS,VERSION_NO DESC;
GO

-- ===== Source: 003_validate_package_workflow.sql =====

SET NOCOUNT ON;

IF SCHEMA_ID(N'workflow') IS NOT NULL
  THROW 51000, 'Legacy workflow schema still exists.', 1;

IF OBJECT_ID(N'dbo.TBLORX', N'U') IS NULL
  THROW 51000, 'Source table dbo.TBLORX was not found.', 1;
IF OBJECT_ID(N'dbo.TBLORXITEMS', N'U') IS NULL
  THROW 51000, 'Source table dbo.TBLORXITEMS was not found.', 1;

IF COL_LENGTH(N'dbo.TBLORXITEMS', N'VISITDATETIME') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.VISITDATETIME was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'VISITNUMBER') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.VISITNUMBER was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'PRESCRIPTIONNUMBER') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.PRESCRIPTIONNUMBER was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'MEDICINECODE') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.MEDICINECODE was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'ITEMSEQ') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.ITEMSEQ was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'IS_DELETED') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.IS_DELETED was not found.', 1;
IF COL_LENGTH(N'dbo.TBLORXITEMS', N'CANCELSTATUS') IS NULL
  THROW 51000, 'Source column TBLORXITEMS.CANCELSTATUS was not found.', 1;

IF OBJECT_ID(N'dbo.TBLWORKFLOWMASTER', N'U') IS NULL
  THROW 51000, 'dbo.TBLWORKFLOWMASTER was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEPRESCRIPTIONS', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEPRESCRIPTIONS was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEMASTER', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEMASTER was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEITEMS', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEITEMS was not created.', 1;
IF OBJECT_ID(N'dbo.TBLPACKAGEEVENTS', N'U') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEEVENTS was not created.', 1;
IF OBJECT_ID(N'dbo.TBLHOSPITALQUEUESTEP', N'U') IS NULL
  THROW 51000, 'dbo.TBLHOSPITALQUEUESTEP was not created.', 1;
IF OBJECT_ID(N'dbo.TBLDISPENSINGCHANNELCLAIMS', N'U') IS NULL
  THROW 51000, 'dbo.TBLDISPENSINGCHANNELCLAIMS was not created.', 1;
IF OBJECT_ID(N'dbo.TBLDRUGLABELTEMPLATES', N'U') IS NULL
  THROW 51000, 'dbo.TBLDRUGLABELTEMPLATES was not created.', 1;
IF COL_LENGTH(N'dbo.TBLPACKAGEMASTER', N'DISPENSING_CHANNEL') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEMASTER.DISPENSING_CHANNEL was not created.', 1;
IF COL_LENGTH(N'dbo.TBLPACKAGEMASTER', N'QUEUE_READY_AT') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEMASTER.QUEUE_READY_AT was not created.', 1;
IF COL_LENGTH(N'dbo.TBLPACKAGEEVENTS', N'ACTION_ID') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEEVENTS.ACTION_ID was not created.', 1;
IF COL_LENGTH(N'dbo.TBLPACKAGEITEMS', N'LABEL_TEMPLATE_ID') IS NULL
  THROW 51000, 'dbo.TBLPACKAGEITEMS.LABEL_TEMPLATE_ID was not created.', 1;

IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_DRAFT') IS NULL
  THROW 51000, 'dbo.TBLWORKFLOWMASTER.VERIFY_NOTE_DRAFT was not created.', 1;
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_AT') IS NULL
  THROW 51000, 'dbo.TBLWORKFLOWMASTER.VERIFY_NOTE_UPDATED_AT was not created.', 1;
IF COL_LENGTH(N'dbo.TBLWORKFLOWMASTER', N'VERIFY_NOTE_UPDATED_BY') IS NULL
  THROW 51000, 'dbo.TBLWORKFLOWMASTER.VERIFY_NOTE_UPDATED_BY was not created.', 1;
GO

-- ===== Source: 006_validate_realtime_sync.sql =====

-- Read-only deployment checks; all tracked tables and both triggers must be enabled.
SELECT DB_NAME() AS DATABASE_NAME, snapshot_isolation_state_desc FROM sys.databases WHERE database_id=DB_ID();
SELECT retention_period,retention_period_units_desc,is_auto_cleanup_on FROM sys.change_tracking_databases WHERE database_id=DB_ID();
SELECT t.name,ct.is_track_columns_updated_on,CHANGE_TRACKING_MIN_VALID_VERSION(t.object_id) AS MIN_VALID_VERSION
FROM sys.tables t LEFT JOIN sys.change_tracking_tables ct ON ct.object_id=t.object_id
WHERE t.name IN ('TBLORX','TBLORXITEMS','TBLPATIENT','TBLMEDITEMSINFO','TBLDOCTOR','TBLDEPT','TBLWORKFLOWMASTER','TBLPACKAGEPRESCRIPTIONS','TBLPACKAGEMASTER','TBLPACKAGEITEMS','TBLREALTIMEINVALIDATIONS','TBLHOSPITALQUEUESTEP','TBLDISPENSINGCHANNELCLAIMS');
SELECT name,is_disabled FROM sys.triggers WHERE name IN ('TR_TBLALLERGY_Realtime','TR_DrugInteraction_Realtime');
SELECT CHANGE_TRACKING_CURRENT_VERSION() AS CURRENT_VERSION;
IF (SELECT COUNT(*) FROM sys.change_tracking_tables WHERE object_id IN (
 OBJECT_ID('dbo.TBLORX'),OBJECT_ID('dbo.TBLORXITEMS'),OBJECT_ID('dbo.TBLPATIENT'),OBJECT_ID('dbo.TBLMEDITEMSINFO'),
 OBJECT_ID('dbo.TBLDOCTOR'),OBJECT_ID('dbo.TBLDEPT'),OBJECT_ID('dbo.TBLWORKFLOWMASTER'),OBJECT_ID('dbo.TBLPACKAGEPRESCRIPTIONS'),
 OBJECT_ID('dbo.TBLPACKAGEMASTER'),OBJECT_ID('dbo.TBLPACKAGEITEMS'),OBJECT_ID('dbo.TBLREALTIMEINVALIDATIONS'),OBJECT_ID('dbo.TBLHOSPITALQUEUESTEP'),OBJECT_ID('dbo.TBLDISPENSINGCHANNELCLAIMS')) AND is_track_columns_updated_on=1)<>13
 THROW 51000,'Realtime tables or column tracking are not fully enabled.',1;
IF (SELECT COUNT(*) FROM sys.triggers WHERE name IN ('TR_TBLALLERGY_Realtime','TR_DrugInteraction_Realtime') AND is_disabled=0)<>2
 THROW 51000,'Realtime clinical alert triggers are not fully enabled.',1;
IF (SELECT snapshot_isolation_state FROM sys.databases WHERE database_id=DB_ID())<>1
 THROW 51000,'Snapshot isolation is not enabled.',1;
GO

PRINT 'JurapornWeb full-stack database installation and validation completed successfully.';

GO

